### ISSUE TITLE
Dub fails with empty ~/.dub/settings.json

### ISSUE THREAD

**Issue by russel** [dlang/dub#1099] opened 2017-03-23 10:01 UTC
If ~/.dub/setting.json is empty then:
```
object.Exception@/usr/include/dmd/phobos/std/stdio.d(808): rawRead must take a non-empty buffer
----------------
??:? ubyte[] std.stdio.File.rawRead!(ubyte).rawRead(ubyte[]) [0x8a8301]
??:? void dub.internal.vibecompat.core.file.RangeFile.rawRead(ubyte[]) [0x899ce8]
??:? ubyte[] dub.internal.vibecompat.core.file.RangeFile.readAll() [0x899c70]
??:? dub.internal.vibecompat.data.json.Json dub.internal.utils.jsonFromFile(dub.internal.vibecompat.inet.path.Path, bool) [0x864902]
??:? void dub.dub.Dub.init() [0x7ead13]
??:? dub.dub.Dub dub.dub.Dub.__ctor(immutable(char)[], dub.packagesupplier.PackageSupplier[], dub.dub.SkipPackageSuppliers) [0x7ea748]
??:? int dub.commandline.runDubCommandLine(immutable(char)[][]) [0x7ced63]
??:? _Dmain [0x7cb5bb]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x95d15e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x95d09c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x95d11a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x95d09c]
??:? _d_run_main [0x95cff9]
??:? main [0x7cdd89]
??:? __libc_start_main [0xde7e75fd]
```

**Comment by andre2007** [comment] 2018-12-11 19:41
Isn't an empty file.json an invalid json? I think about what the correct solution is for this issue. Maybe the Error message should be adapted, but it seems technically correct to abort dub.

@russel What is your expectation?

**Comment by Samathy** [comment] 2019-05-02 22:16
Hi, 

I've confirmed this is still an issue and am looking to fix it ( A coincidence I picked one of your issues @russel,  honest! ).

I propose the following solution - Update jsonFromFile to [test if the string is empty before trying to parse it. ](https://github.com/dlang/dub/blob/5489b0926bb1f408600684d77d7568fbba8da1b6/source/dub/internal/utils.d#L129)

Assigning myself, will create a PR with this solution unless there is other suggestions in the near future :)

**Comment by Samathy** [comment] 2019-05-02 22:47
Looks like its actually the [readAll](https://github.com/dlang/dub/blob/5489b0926bb1f408600684d77d7568fbba8da1b6/source/dub/internal/utils.d#L127) method which fails. Maybe a `try/catch` around that ( respecting `silent_fail` ) would be more appropriate, unless there is anyway of testing the file is empty before reading it.

But I'll look into it more soon.

**Comment by Geod24** [comment] 2022-08-21 18:48
Fixed with the latest master:
![image](https://user-images.githubusercontent.com/2180215/185806301-f9d770f6-c917-4e19-81f3-d750a5a6754c.png)

Most likely thanks to https://github.com/dlang/dub/pull/2343

**Closed by Geod24** 2022-08-21 18:48 UTC
Labels: bug

**Comment by WebFreak001** [comment] 2022-08-22 12:23
"Zero documents in stream" seems like a weird error message for this. Should probably update that? @Geod24

**Comment by Geod24** [comment] 2022-08-22 12:29
Indeed. What should be the behavior here ? Silence, warning, proper error message ?

**Comment by WebFreak001** [comment] 2022-08-22 12:54
proper error message like `File "/path/to/whatever.json" is not a valid JSON document`
