### ISSUE TITLE
dub gets into infinite loop

### ISSUE THREAD

**Issue by carun** [dlang/dub#1345] opened 2018-01-20 19:18 UTC
### System information

- **dub version**: master, 1.7.0, 1.6.0
- **OS Platform and distribution**: Ubuntu 17.10 64 bit, Ubuntu 16.04 64 bit
- **compiler version** (e.g. dmd-2.077.1)

### Bug Description
DUB gets into an infinite while loop for pretty much any operation) dub clean --all-packages, dub build, dub upgrade, etc).

### How to reproduce?
A repo to reproduce: https://github.com/carun/dub-error

### Expected Behavior
dub should not get into indefinite loop

### Logs
Strace has been uploaded here: https://drive.google.com/open?id=1GgLIw1dCCpY0STsfwmlaivAgXDLERO96

**Comment by carun** [comment] 2018-01-22 21:16
Adding the code here, just in case the repo to reproduce gets deleted in future

* D code
```d
import std.stdio;
import darg;

private struct Options {
    @Option("help", "h")
    @Help("Prints this help.")
    OptionFlag help;
}

// Generate the usage and help string at compile time.
private immutable usage = usageString!Options("test-client");
private immutable help = helpString!Options;

void main(string[] args) {
    __gshared Options options;
    try {
        options = parseArgs!Options(args[1 .. $]);
    }
    catch (ArgParseError e) {
        writeln(e.msg);
        writeln(usage);
        return;
    }
    catch (ArgParseHelp e) {
        // Help was requested
        writeln(usage);
        write(help);
        return;
    }

    return get(options);
}

private void get(in ref Options options) {
    immutable url = "http://www.google.com";
    import std.net.curl : get;
    const res = get(url);
    import std.json : parseJSON;
    writeln(res.parseJSON.toPrettyString);
}
```

* dub.json
```json
{
    "name": "test-client",
    "authors": [
        "Arun Chandrasekaran"
    ],
    "dependencies" : {
        "darg": "~>0.0.4",
        "dproto": "~>2.1.3",
        "painlessjson": "~>1.3.8",
        "requests": "~>0.6.0"
    },
}
```

**Comment by carun** [comment] 2018-01-22 22:40
Got this error message today after I left to run for 10 mins:

```
The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.
```

**Comment by rjframe** [comment] 2018-01-22 23:42
`dub build -v` gives the following output: https://gist.github.com/rjframe/ef8ecfb9c92a83d69c78d555fc504b08

The end of that output:

```
Search for versions of dproto (1 package suppliers)
Ignoring version specification (>=0.0.0) for path based dependency ..
[[ this line repeats a lot]]
Ignoring version specification (>=0.0.0) for path based dependency ..
Return for dproto: [2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.2, 2.0.1, 2.0.0, 1.3.2, 1.3.1, 1.3.0, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.0, ~master, ~error-lines, ~dev-1.x]
Search for versions of painlesstraits (1 package suppliers)
Return for painlesstraits: [0.3.0, 0.2.0, 0.1.0, 0.0.3, 0.0.2, 0.0.1, ~master]
Search for versions of painlessjson (1 package suppliers)
Return for painlessjson: [1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.1, 1.0.0, 0.7.0, ~master]
Search for versions of dunit (1 package suppliers)
Return for dunit: [1.0.14, 1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-beta, ~master]
Search for versions of darg (1 package suppliers)
Return for darg: [0.0.4, 0.0.3, 0.0.2, 0.0.1, ~master]
```

It hangs after darg.

This occurs for me on Windows (dub 1.3.0) and Linux (Dub 1.6.0).

**Comment by drug007** [comment] 2018-01-23 01:51
Probably the same #1001

**Comment by MartinNowak** [comment] 2018-01-27 12:15
It's iterating over all the possible dependency versions and can't seem to easily find a satisfiable resolution. The numbers grows exponentially `darg x dproto x painlessjson x requests x recursive-deps`, so it's not easily solveable.

The dependency resolver usually runs into pathological cases when the versions are overly constrained or contradicting, so that it cannot use the latest version but has to iterate through alternatives or even exhaust all possible combinations.

A simple **workaround** for your package, change painlessjson to a less strict requirement

    "painlessjson": "~>1.3"

or

    "painlessjson": "~>1.3.0"

, both will resolve to `1.3.5`.

The root cause is that dproto requires [`painlesstraits: ~>0.3.0`](https://github.com/msoucy/dproto/blob/v2.1.4/dub.json#L22) while painlessjson 1.3.6 introduces a contradicting [`painlesstraits: ~>0.1.0`](https://github.com/BlackEdder/painlessjson/blob/v1.3.6/dub.json#L10). 
Painlessjson 1.3.5 does not depend on painlesstraits, hence that would be a valid resolution, but the OP package requires `painlessjson: ~>1.3.8`, hence there is no valid dependency resolution at all.

The dependency resolver gets stuck on exhaustively iterating through all combinations to figure that out. Not easy to improve over brute-force unfortunately, e.g. an newer version of a package could contain a downgraded dependency.

**Comment by andre2007** [comment] 2018-10-24 18:31
Cannot reproduce the issue with dub 1.9.0
Can this issue be closed?

**Comment by denizzzka** [comment] 2018-10-28 09:51
Faced with same issue:

```
[...]
Search for versions of stalkd (1 package suppliers)
Return for stalkd: [1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0, ~master]
Search for versions of drmi (1 package suppliers)
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency ./drmi
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Ignoring version specification (>=0.0.0) for path based dependency .
Return for drmi: [0.13.0, 0.12.1, 0.12.0, 0.11.1, 0.11.0, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.2, 0.8.1, 0.8.0, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.0, 0.1.1+fix, 0.1.0+fix, 0.6.0-alpha.1, ~master]
Search for versions of stringbuffer (1 package suppliers)
Return for stringbuffer: [1.1.2, 1.1.1, 1.1.0, 1.0.0, ~master]
Search for versions of fastjwt (1 package suppliers)
Return for fastjwt: [1.0.0, 0.0.2, 0.0.1, ~master]
Search for versions of yamlserialized (1 package suppliers)
Return for yamlserialized: [0.3.0, 0.2.0, 0.1.1, 0.1.0, ~master]
Search for versions of dunit (1 package suppliers)
Return for dunit: [1.0.14, 1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-beta, ~master]
The dependency resolution process is taking too long. The dependency graph is likely hitting a pathological case in the resolution algorithm. Please file a bug report at https://github.com/dlang/dub/issues and mention the package recipe that reproduces this error.
```

**Comment by mathemaphysics** [comment] 2019-05-27 20:45
This is exactly what happens to me when I try anything with vibe-d. Anything at all. I've tried using `vibe-d` as the *only* dependency and this happens. Once I remove it, everything is fine.

**Comment by ZombineDev** [comment] 2019-05-28 04:43
Make sure you're using the latest version of dub, where those problems were fixed.

**Comment by Geod24** [comment] 2019-12-27 02:23
https://github.com/dlang/dub/issues/1345#issuecomment-359567360

Tested with dub 1.17.0 (v2.088.1) on Mac OSX after removing everything in my local cache:
```console
$ dub build
Fetching dproto 2.1.5 (getting selected version)...
Fetching painlesstraits 0.3.0 (getting selected version)...
Fetching vibe-core 1.8.1 (getting selected version)...
Fetching requests 0.6.0 (getting selected version)...
Fetching taggedalgebraic 0.11.8 (getting selected version)...
Fetching botan-math 1.0.3 (getting selected version)...
Fetching painlessjson 1.3.9 (getting selected version)...
Fetching vibe-d 0.8.6 (getting selected version)...
Fetching memutils 0.4.13 (getting selected version)...
Fetching stdx-allocator 2.77.5 (getting selected version)...
Fetching botan 1.12.10 (getting selected version)...
Fetching diet-ng 1.6.0 (getting selected version)...
Fetching dunit 1.0.15 (getting selected version)...
Fetching darg 0.0.5 (getting selected version)...
Fetching openssl 1.1.6+1.0.1g (getting selected version)...
Fetching eventcore 0.8.48 (getting selected version)...
Fetching mir-linux-kernel 1.0.1 (getting selected version)...
Fetching libevent 2.0.2+2.0.16 (getting selected version)...
Fetching libasync 0.8.4 (getting selected version)...
Performing "debug" build using dmd for x86_64.
darg 0.0.5: building configuration "library"...
dunit 1.0.15: building configuration "library"...
painlesstraits 0.3.0: building configuration "unittest"...
painlessjson 1.3.9: building configuration "library"...
[... Lots of deprecations ... ]
test-client ~master: building configuration "application"...
Linking...
dub build  9.16s user 2.96s system 24% cpu 49.630 total
```

`dub upgrade` also works.

https://github.com/dlang/dub/issues/1345#issuecomment-433690743

Tested this as well (same thing, removed `dub.selections.json` and `~/.dub/packages/*`):
```console
$ dub build
Fetching botan-math 1.0.3 (getting selected version)...
Fetching stringbuffer 1.1.2 (getting selected version)...
Fetching taggedalgebraic 0.11.8 (getting selected version)...
Fetching drmi 0.13.0 (getting selected version)...
Fetching vibe-d-postgresql 2.0.3 (getting selected version)...
Fetching fastjwt 1.1.1 (getting selected version)...
Fetching eventcore 0.8.48 (getting selected version)...
Fetching libasync 0.8.4 (getting selected version)...
Fetching tinyendian 0.1.2 (getting selected version)...
Fetching money 2.3.1 (getting selected version)...
Fetching vibe-d 0.8.6 (getting selected version)...
Fetching botan 1.12.10 (getting selected version)...
Fetching dunit 1.0.15 (getting selected version)...
Fetching yamlserialized 0.3.0 (getting selected version)...
Fetching libevent 2.0.2+2.0.16 (getting selected version)...
Fetching dpq2 1.0.11 (getting selected version)...
Fetching vibe-core 1.8.1 (getting selected version)...
Fetching requests 0.7.4 (getting selected version)...
Fetching diet-ng 1.6.0 (getting selected version)...
Fetching openssl 1.1.6+1.0.1g (getting selected version)...
Fetching derelict-util 3.0.0-beta.2 (getting selected version)...
Fetching memutils 0.4.13 (getting selected version)...
Fetching stdx-allocator 2.77.5 (getting selected version)...
Fetching derelict-pq 4.0.0-alpha.2 (getting selected version)...
Fetching dyaml 0.6.5 (getting selected version)...
Fetching mir-linux-kernel 1.0.1 (getting selected version)...
Fetching stalkd 1.1.3 (getting selected version)...
Running pre-generate commands for vibe-d:tls...
Performing "debug" build using dmd for x86_64.
drmi:ssll 0.13.0: building configuration "library"...
drmi:mosquitto 0.13.0: building configuration "rtload"...
tinyendian 0.1.2: building configuration "library"...
dyaml 0.6.5: building configuration "library"...
[ ... Irrelevant build failure ... ]
dmd failed with exit code 1.
dub build  3.90s user 2.70s system 9% cpu 1:07.13 total
```

Closing as it works now.

**Closed by Geod24** 2019-12-27 02:23 UTC
Labels: 2-re, diagnostic
