### ISSUE TITLE
Suggestion: Compiler Compatibility Specifiers

### ISSUE THREAD

**Issue by dymk** [dlang/dub#108] opened 2013-09-03 22:39 UTC
Some projects won't compile with older versions of DMD. I suggest that a setting be added to package.json to specify compatibility with compiler versions: 

``` json
{
    "compilers": {
        "dmd": ">= 2.063", // Requires DMD 2.063 or greater
        "ldc": {
            "not": "1.34"    // Not version 1.34 of LDC (could be an array)
        },
        "gdc": {
            "only": ["2.062", "2.064"] // Only versions 2.062 and 2.064 of GDC (could be a string)
        }
    }
}
```

If a compiler is not listed in the "compilers" map, then no warnings are emitted for it. Eg, if there was support for a compiler called "wmc", but there was no "wmc" key in "compilers", there would be no warning. 

If it is, compilation isn't halted, but a warning is printed to the console, such as `Warning: Incompatible compiler detected: <Compiler Name> <Compiler Version>`

I've come across a few instances now where it'd be useful to specify compiler compatibility, mostly when dealing with how CTFE differs across versions in DMD.

Perhaps it could also be listed as "compatibility notes" or something in the table of packages on code.dlang.org, so people can quickly get an idea of if they can use a project or not. 

Thoughts?

**Comment by qznc** [comment] 2015-08-06 18:55
Here is an example, where it would have help to specify a minimum compiler version: https://github.com/Hackerpilot/dfmt/issues/132

I agree that "dmd version" is not actually what we want to specify. There is no "language version", though. Is there a way to map "dmd version" to the corresponding ldc/gdc version?

**Comment by bruno-medeiros** [comment] 2015-08-20 14:00
If one considers the D language to include the Phobos (which I think one should), then the first two numbers of the DMD version (ie, "2.063" of "2.063.1") are indeed a language version. Not only because of the standard library, but because minor version numbers can introduce language changes.

**Comment by MartinNowak** [comment] 2017-07-05 11:26
> I agree that "dmd version" is not actually what we want to specify. There is no "language version", though. Is there a way to map "dmd version" to the corresponding ldc/gdc version?

Yes, `pragma(msg, __VERSION__);` works on all of them.
Examples 2068, 2070, 2072.

Specifying that at least `d-frontend >= 2.063` is needed would indeed be helpful for new D or phobos features.
If phobos versioning starts to differ from dmd versioning, we'd need an additional specifier.

**Comment by wilzbach** [comment] 2017-09-13 01:34
Closing as duplicate of#654

**Comment by s-ludwig** [comment] 2017-09-13 11:06
#654 is about the version of DUB vs. the version of the compiler, so we'll have to keep this open, too.

**Comment by wilzbach** [comment] 2017-09-13 11:15
I don't think it's different because dub is now released with DMD / LDC with at least the version of the current release (the LDC people ship a newer dub with their "old" 2.07x release), but the main points were that
- allowing to specify a minimal D version also implies a minimal DUB version
- dub got much more stable over the last two years
- the D version is much more likely to break things

**Comment by wilzbach** [comment] 2017-09-13 11:18
Also there is another duplicate: https://github.com/dlang/dub/issues/863

**Comment by s-ludwig** [comment] 2017-09-13 11:55
> - allowing to specify a minimal D version also implies a minimal DUB version

I don't think this holds in practice. You'll quite often have a single version of DUB that is used to drive DMD, GDC and LDC alike. A prominent example would be the Travis-CI setups that use the latest DUB release, and may still need to test ancient compilers.

> - dub got much more stable over the last two years
> - the D version is much more likely to break things

These are probably true, but DUB generally still gets new features, so that it may still make sense to specify a minimum version.

**Comment by andre2007** [comment] 2018-10-24 18:54
See pull request https://github.com/dlang/dub/pull/1571

**Comment by wilzbach** [comment] 2019-05-10 09:40
https://github.com/dlang/dub/pull/1571 has been merged and shipped now, so we can close this (:

**Closed by wilzbach** 2019-05-10 09:40 UTC
Labels: enhancement
