### ISSUE TITLE
dub now takes 2x longer to compile

### ISSUE THREAD

**Issue by ryuukk** [dlang/dub#2600] opened 2023-02-17 21:36 UTC
### System information

- **dub version**: ~master
- **OS Platform and distribution**: Windows 10 x64
- **compiler version**: dmd v2.102.0 (DUB version 1.31.0, built on Feb  1 2023)

### Bug Description

dub compiles in 10 seconds

### How to reproduce?

```
time dub build -f
```

### Expected Behavior

Previous version: v1.29.2 compiles in 5 seconds

It now is 2x slower...

D compiles fast, yet all the community projects compiles very slow

EDIT:

to clarify: i am compiling the dub repo with dub that comes with "dmd v2.102.0"

**Comment by Geod24** [comment] 2023-02-17 23:07
Timing a from-scratch build is not really a fair assessment. Absolute compile time is not as important as incremental one.
Also, the reason why dub is much slower to compile is, I believe, that there is much more code now in the project (D-YAML, Configy) and much more templates. I'm tempted to close this as WONTFIX, @WebFreak001 ?

**Comment by s-ludwig** [comment] 2023-02-18 08:36
I'd also say that the Configy code and its instantiations are probably the reason. It's just really easy to push compile times like that with introspection heavy code. But although I'm not a big fan of this approach within this particular project (cost/complexity vs. benefit), I wouldn't classify the compile time issue itself as very severe and would generally be tempted to concur with @Geod24.

On the other hand, maybe there are a few easy targets within the code to make it compile faster, which could be a worthwhile investment that also benefits the original library. `dmd -vtemplates` might provide a good starting point here.

**Comment by s-ludwig** [comment] 2023-02-20 08:32
> `Serializing composite type Flags!(BuildRequirement) which has no serializable fields`

(This is something that needs to be looked into, might be a bug.)

**Comment by WebFreak001** [comment] 2023-02-20 08:48
> I'd also say that the Configy code and its instantiations are probably the reason. It's just really easy to push compile times like that with introspection heavy code. But although I'm not a big fan of this approach within this particular project (cost/complexity vs. benefit), I wouldn't classify the compile time issue itself as very severe and would generally be tempted to concur with @Geod24.
> 
> On the other hand, maybe there are a few easy targets within the code to make it compile faster, which could be a worthwhile investment that also benefits the original library. `dmd -vtemplates` might provide a good starting point here.

We should really start looking into using dub to build dub with dependencies, or at least use dub on the bootstrapping system to download dependencies and generating the compile command.

It'd also be nice to not need to vendor all the extra dependencies this way and would add some compilation cache for dependencies.

We could also make the recipe parsing a separate submodule, which imo makes sense anyway.

I'm with ryuukk here that we should be doing something about this.

@s-ludwig @Geod24 what are your opinions about using dub dependencies on dub?

Other advantages:

- the mental threshold to add new dependencies for cool features lowers, making it more likely that users would just try out dependencies for features
- no need to double maintain bug fixes and improvements

**Comment by Geod24** [comment] 2023-02-20 08:57
> what are your opinions about using dub dependencies on dub?

https://github.com/dlang/dub/pull/1972

**Comment by WebFreak001** [comment] 2023-03-09 17:49
we have comments on PRs now that show a rough build time and executable size, so it's easier to reason about PRs to (significantly) improve on build times now.

**Comment by WebFreak001** [comment] 2023-09-23 12:02
yeah really need to improve the compiler for that stuff

**Comment by Geod24** [comment] 2023-12-28 22:56
@ryuukk : I appreciate you spending the time to look into the issue and to report it. And any PR that provably improve compile speed without hurting code quality / functionality / abstraction is very welcome.

On the other hand, I am trying to keep issues focused on actionable items. Keeping compile time low is IMO a continuous process (like keeping code readable / abstraction clear) which is not well captured by an issue. In this case, an actionable item would be something such as "Get dub to compile in less than 5 seconds". However, there isn't much value in such an issue - it is indeed better for the development experience, but it does not accomplish anything for the end user. Hence I am going to close this as WONTFIX - which doesn't mean, as stated above, that improvements are not encouraged.

**Closed by Geod24** 2023-12-28 22:55 UTC

**Comment by Geod24** [comment] 2023-12-29 11:03
If the issue is that dub is slower to compile projects, then we should definitely re-open this issue.

However I am going off your original post:
> to clarify: i am compiling the dub repo with dub that comes with "dmd v2.102.0"

The increase in compile time for dub itself is not as worrying as an increase across the board. For reference, I have been working on improving dub compile time across the board, mostly with improvements to the `PackageManager` (See  https://github.com/dlang/dub/issues/2338) and the central build cache. And when I introduced the new config reading framework, I timed it, and while it did have an impact, the impact wasn't that much.

To test if Dub compile time has increased, we need to test the same codebase with the same compiler:
```
% ~/dlang/dmd-2.100.0/linux/bin64/dub --version
DUB version 1.29.0, built on May 13 2022
% ~/dlang/dmd-2.106.0/linux/bin64/dub --version
DUB version 1.35.0, built on Dec  2 2023
```
This should be a good baseline, as most of my improvements came in v1.30.0. I'm using DMD v2.106 to compile, got them using the install script.

Older dub:
```
% time ~/dlang/dmd-2.100.0/linux/bin64/dub build --compiler=$HOME/dlang/dmd-2.106.0/linux/bin64/dmd
Performing "debug" build using /home/mlang/dlang/dmd-2.106.0/linux/bin64/dmd for x86_64.
dub 1.35.0-rc.1+commit.44.g56077da3: building configuration "application"...
[...]
Linking...
~/dlang/dmd-2.100.0/linux/bin64/dub build   4.84s user 1.14s system 95% cpu 6.266 total
```

Newer dub:
```
% time ~/dlang/dmd-2.106.0/linux/bin64/dub build --compiler=$HOME/dlang/dmd-2.106.0/linux/bin64/dmd
    Starting Performing "debug" build using /home/mlang/dlang/dmd-2.106.0/linux/bin64/dmd for x86_64.
    Building dub 1.35.0-rc.1+commit.44.g56077da3: building configuration [application]
[...]
     Linking dub
~/dlang/dmd-2.106.0/linux/bin64/dub build   4.94s user 1.23s system 98% cpu 6.264 total
```

I also made sure to clean up both caches (`.dub` for the old version, `~/.dub/cache/dub/*` for the new version).
Obviously you should measure more than once, so for older dub:
```
% time ~/dlang/dmd-2.100.0/linux/bin64/dub build --compiler=$HOME/dlang/dmd-2.106.0/linux/bin64/dmd && rm -rf .dub
~/dlang/dmd-2.100.0/linux/bin64/dub build   5.40s user 1.04s system 98% cpu 6.510 total
~/dlang/dmd-2.100.0/linux/bin64/dub build   5.28s user 1.29s system 99% cpu 6.613 total
~/dlang/dmd-2.100.0/linux/bin64/dub build   5.37s user 1.22s system 98% cpu 6.671 total
~/dlang/dmd-2.100.0/linux/bin64/dub build   5.11s user 1.00s system 98% cpu 6.191 total
```
And for newer dub:
```
% time ~/dlang/dmd-2.106.0/linux/bin64/dub build --compiler=$HOME/dlang/dmd-2.106.0/linux/bin64/dmd && rm -rf ~/.dub/cache/dub/
~/dlang/dmd-2.106.0/linux/bin64/dub build   5.34s user 1.44s system 99% cpu 6.834 total
~/dlang/dmd-2.106.0/linux/bin64/dub build   4.66s user 1.10s system 98% cpu 5.840 total
~/dlang/dmd-2.106.0/linux/bin64/dub build   4.89s user 1.28s system 98% cpu 6.270 total
~/dlang/dmd-2.106.0/linux/bin64/dub build   5.22s user 1.09s system 98% cpu 6.381 total
```

As you can see, the best time for the new dub is 300 ms faster than for the old dub. That does not seem to support the claim that dub is slower at compiling projects.

Now if we talking dub's own compile time, yes it has gone up:
```
% time ~/dlang/dmd-2.106.0/linux/bin64/dub build --compiler=$HOME/dlang/dmd-2.106.0/linux/bin64/dmd && rm -rf ~/.dub/cache/dub/
    Starting Performing "debug" build using /home/mlang/dlang/dmd-2.106.0/linux/bin64/dmd for x86_64.
    Building dub 1.29.0: building configuration [application]
Serializing composite type BuildRequirements which has no serializable fields
Serializing composite type BuildOptions which has no serializable fields
     Linking dub
~/dlang/dmd-2.106.0/linux/bin64/dub build   2.86s user 0.65s system 97% cpu 3.597 total
 % git describe
v1.29.0
```
