### ISSUE TITLE
dub install executables

### ISSUE THREAD

**Issue by Extrawurst** [dlang/dub#1046] opened 2017-01-15 12:18 UTC
the docs say 
```
Note: DUB does not do a system installation of packages. Packages are instead only registered within DUB's internal ecosystem. Generation of native system packages/installers may be added later as a separate feature.
```

I think we should approach this issue. I like to get on par with npm in this regard. Let us use this ticket to discuss how to design this.

npm uses shell scripts that get sym-linked into a .npm/bin folder. question is now for me, whether to also host rdmd shell scripts as 'binaries' (similar to npm approach, introducing a potential long compilation on first run) or build the binary directly when invoking dub-install?

What do you think @s-ludwig ?

**Comment by WebDrake** [comment] 2017-01-29 18:14
Note this isn't just a convenience for people wanting to both build and install projects locally.  It also makes it easier to use dub with many packaging tools, which expect an `install` option to be available.

Also, note that `install` isn't just useful for executables: it could also be useful for libraries and even source libraries.

**Comment by MartinNowak** [comment] 2017-12-23 15:54
Duplicate of #839

**Closed by MartinNowak** 2017-12-23 15:54 UTC
