### ISSUE TITLE
Global user configuration

### ISSUE THREAD

**Issue by FreeSlave** [dlang/dub#557] opened 2015-04-27 21:36 UTC
Is it possible to set global user configuration?
It would be handy to set default author's name, license, copyright and homepage to fill the newly initialized dub.json with them without the need for copy-pasting.

**Comment by gedaiu** [comment] 2015-04-28 06:54
I don't think so... but this might be a good ideea... what are the variables that you think that should be set globally?

**Comment by MyLittleRobo** [comment] 2015-04-28 07:43
These fields are author's name, copyright string, license (useful, if programmer uses the same license for all projects), and probably homepage.
Also it would be nice to set default .gitignore to generate (e.g. I usually set to ignore bin/ and lib/ directories, *.exe and other binary files).

**Comment by MrSmith33** [comment] 2015-04-29 22:55
Maybe there should be an example project which will be copied when user inits new package. Then you can add any files `i.e. .gitignore`, or `default author's name, license, copyright and homepage` right into dub.json.

**Comment by greenify** [comment] 2016-04-07 16:25
I think this is a good idea, other variables that might be interesting for a global config file are registry location, cache directory or verbosity.

**Comment by wilzbach** [comment] 2017-09-13 01:15
Closing as duplicate of https://github.com/dlang/dub/issues/590

**Closed by wilzbach** 2017-09-13 01:15 UTC
