### ISSUE TITLE
dependencies being pulled for unused configurations 

### ISSUE THREAD

**Issue by cyisfor** [dlang/dub#844] opened 2016-05-14 19:20 UTC
dub is pulling all dependencies from all configurations, even if a particular configuration is selected.

To reproduce:
$ clone https://github.com/buggins/ddbc
$ dub -v build --config=SQLite
...
Search for versions of mysql-native (1 package suppliers)
...
Fetching mysql-native 0.1.4 (getting selected version)...
...

This is probably a similar issue to #831.

**Comment by Geod24** [comment] 2022-07-27 19:34
Duplicate of either #1217 or #1706

**Closed by Geod24** 2022-07-27 19:34 UTC
Labels: duplicate
