### ISSUE TITLE
Add a run command that doesn't do any building.

### ISSUE THREAD

**Issue by skl131313** [dlang/dub#1027] opened 2016-12-20 23:35 UTC
When wanting to run a package once it's built, the run command shouldn't continually need to be given specific compile commands that aren't needed for running the program. Simply running the package that was built would be fine. Potentially adding an actual "install" feature that adds the built binary into the system's path to be used. So instead of `dub run-only <package>` you could just do `<package-executable>`.

**Comment by p0nce** [comment] 2016-12-21 11:51
Because of caching a `run-only` command wouldn't be any faster than `dub run` so the purpose would only be to avoid typing switches? Can elaborate what are the switches you have to type repeatedly?

As a concept "run" is not precise. Do you want "run with debug info", "run with optimizations", "run for 32-bit arch", "run for 64-bit arch"? It make sense to have some of that required.

Note that if you don't want to hit the network, you can use `--skip-registry=all`.

**Comment by sprinkle131313** [comment] 2016-12-21 18:18
It could use the last built one, though that would annoying if you want to build and still use the other one. It's not really about caching, so much as when I want to run a command I don't want to specify which build every time.

Having an install feature would fix the problem. You can choose which build specifically to use when installing. Then you wouldn't need to go through dub to run the package.

**Comment by andre2007** [comment] 2019-08-19 21:27
Duplicate of https://github.com/dlang/dub/issues/839

**Closed by andre2007** 2019-08-19 21:27 UTC
