### ISSUE TITLE
Disallow Trailing Commas in dub.json

### ISSUE THREAD

**Issue by nordlow** [dlang/dub#415] opened 2014-09-07 20:15 UTC
As trailing commas are not accepted by the standard then maybe DUB shouldn't accept it either:

https://stackoverflow.com/questions/201782/can-you-use-a-trailing-comma-in-a-json-object

This can be confusing to D newcomers who want to use Emacs for their D development. The error occurs in Emacs' standard library so its very hard to understand what is wrong.

See also discussion at https://github.com/atilaneves/flycheck-dmd-dub/issues/5

**Comment by wilzbach** [comment] 2017-09-13 01:22
Closing this as a duplicate of https://github.com/dlang/dub/issues/1205 (while GitHub allows to mark this, I don't see any reason in keeping two issues open for the same goal)

**Closed by wilzbach** 2017-09-13 01:22 UTC
