### ISSUE TITLE
Dub install

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1741] opened 2019-07-23 09:32 UTC
In a Dockerfile I have following instructions:

```# Install helloworld
COPY d/ /opt/helloworld/d/
RUN dub build --root opt/helloworld/d/ \
    && echo "#!/bin/bash" > /usr/bin/helloworld \
    && echo "dub run --root /opt/helloworld/d/ --vquiet -- \$@" >> /usr/bin/helloworld \
    && chmod +x /usr/bin/helloworld

# Prepare appuser
RUN addgroup --gid 1001 appuser && adduser --uid 1001 --gid 1001 --disabled-password --gecos '' appuser
USER appuser
```

1. A dub project is copied to /opt/helloworld/d/
2. The dub project is built with root user. If the package is build in a later step with appuser, this would fail, as appuser has no write permission to /opt/helloworld/d/
3. A bash script is written to /usr/bin/ which will execute ```dub run --root /opt/helloworld/d/ --vquiet -- $@```. The bash script also gets executable permission
4. appuser is created and set as default user for security reasons

While this Dockerfile is working fine, it is highly complex and quite hard to get it working for an inexperienced user. Maybe the RUN line can be replaced with ```dub install --root opt/helloworld/d/```. It could build the application and automatically create a bash script in ```~/.dub/scripts```.
The folder ```~/.dub/scripts``` you could then add to PATH variable in Dockerfile via ENV statement.

**Comment by Geod24** [comment] 2019-08-02 04:31
It sounds to me that this should be two separate stages: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by wilzbach** [comment] 2019-08-02 04:45
Yup, multi-stage builds for the win.
Here's an example I use for a minimal D microservice: https://github.com/microservices/d/blob/master/Dockerfile

**Comment by wilzbach** [comment] 2019-08-02 04:47
For the install command, see https://github.com/dlang/dub/issues/839.
Closing as duplicate of that issue.

**Closed by wilzbach** 2019-08-02 04:47 UTC
Labels: enhancement
