### ISSUE TITLE
Remove workaround for package.d

### ISSUE THREAD

**Issue by gizmomogwai** [dlang/dub#2223] opened 2022-02-20 16:05 UTC
Hi, I have a simple dub package, that only has one source file (with unittests) in source/dub-package-name/package.d.
I wanted to switch its unit testrunner to silly (which makes use of the dub_test_root module) and my tests are not discovered.
Digging through dubs source I found https://github.com/dlang/dub/blob/c2c6735308986253d7f600d90fc151cd86a350cb/source/dub/dub.d#L720 which points to https://issues.dlang.org/show_bug.cgi?id=11847. The bugzilla bug seems to be fixed since 2020, would it be possible to also remove this workaround?

**Comment by WebFreak001** [comment] 2022-02-20 21:14
duplicate of #424 and #1874

**Closed by WebFreak001** 2022-02-20 21:14 UTC
