### ISSUE TITLE
DRT runtime option affect dub, not the spawned program

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [dlang/dub#1280] opened 2017-11-02 16:23 UTC
### System information
- DUB version 1.5.0, built on Oct  9 2017
- Ubuntu 16.04
- DMD64 D Compiler v2.076.1

### Bug Description
Invoking a program using `dub -- --DRT-oncycle=ignore` (or any other DRT option) will affect `dub`, and not the built program, as intended.

### Expected Behavior
- The DRT option applies to the child process
- The DRT option does not apply to dub

I am unsure if this is a druntime bug or not. Passing the arguments to the spawned program is easy, but excluding it from dub is hard, as `dub --DRT-oncycle=print -- --DRT-oncycle=ignore` should work. [There is a way to disable automatic parsing of those options](https://github.com/dlang/druntime/blob/321b0b094b97ac66a0595112c9826e10c243ba95/src/rt/config.d#L20-L23) but I'm not sure there is one to process them after initialization.

CC @MartinNowak

**Comment by s-ludwig** [comment] 2017-11-05 16:01
I guess for practical reasons it would be reasonable to simply disable parsing for DUB itself (when built as an executable), or at least I don't think that there is much reason for using those options for this kind of short-lived command line application.

**Comment by andre2007** [comment] 2018-11-25 19:00
In druntime this pull request was merged https://github.com/dlang/druntime/pull/2375
If my understanding is correct, dub can add this line ```extern(C) __gshared bool rt_cmdline_enabled = false;``` to avoid ```--DRT...``` arguments are consumed by dub instead of the app.

**Comment by Geod24** [comment] 2019-12-19 17:28
I looked into Vladimir's fix, but I think it is just the problem, until I missed something. I commented on the PR. Thanks for the link!

**Comment by andre2007** [comment] 2019-12-22 19:20
This bug will likely causes issues for e.g. unittest frameworks which relies on a main function. With recent dmd the default was changed, and solution is to pass --DRT argument, which is not possible due to this bug.

**Comment by schveiguy** [comment] 2019-12-22 23:32
> This bug will likely causes issues for e.g. unittest frameworks which relies on a main function

As I mentioned in the forums, the frameworks need to override the default unittest behavior anyway. Otherwise, unittests will be run before main is reached (which defeats the purpose of having an alternate framework). So this will not be an issue.

But on the topic at hand, I think dub 100% needs to ignore all DRT options, and pass them through as intended. This can be behind a debug version, if one needs to do something like profile dub's memory usage. The shipping binary should pass-through the switches.

**Comment by Geod24** [comment] 2019-12-22 23:40
> But on the topic at hand, I think dub 100% needs to ignore all DRT options, and pass them through as intended.


Why not just go with https://issues.dlang.org/show_bug.cgi?id=20459 ?

**Comment by schveiguy** [comment] 2019-12-23 02:07
I don't see the use case. dub is a build tool, and a tool for running applications. I shouldn't have to work around the runtime when I run dub. If I want to profile dub's GC memory, or change dub's unittest options, I can build a special version of dub.

rdmd should be the same as well.

**Comment by Geod24** [comment] 2019-12-23 03:14
> I don't see the use case. dub is a build tool, and a tool for running applications. I shouldn't have to work around the runtime when I run dub. If I want to profile dub's GC memory, or change dub's unittest options, I can build a special version of dub.

I see it more as a way to avoid special casing.
Regardless of `dub` or not, having druntime eating arguments to the program based on a magic string, and the only resort to avoid it being to recompile the binary is incredibly developer-centric (as opposed to user centric).

If we acknowledge the need for end-users to configure the runtime without recompilation (which is the point of `--DRT` options), then we need a way to turn it off, and the POSIX argument delimiter sounds like the most natural option. 

I don't see how having a feature that does not compose is can be desirable.

**Comment by schveiguy** [comment] 2019-12-23 04:09
Yes, it's a good feature for druntime to support. But dub shouldn't be in the business of eating options you want to pass to the program you want to run. We can do both.

BTW, I don't think `--` is right. That's way way too common a feature, and you are going to start interfering with the regular options. I'd say something like `--DRT--` would be more appropriate.

**Comment by Geod24** [comment] 2019-12-23 04:16
> That's way way too common a feature

Isn't that the point ? That arguments after `--` aren't options, but just positional text arguments ?

> I'd say something like `--DRT--` would be more appropriate.

The would mean `dub run --DRT-gcopt="parallel:0" -- program_argument --somearg --DRT-- --DRT-gcopt="..."`

**Comment by schveiguy** [comment] 2019-12-23 05:18
> Isn't that the point ? That arguments after `--` aren't options, but just positional text arguments ?

It just feels wrong to have no way to instruct the parameters to druntime without also limiting the processing on the main program. If I want the program to receive the options " --DRT-gcopt=profile:1 -- --anotherThing", how do I do it?

And for dub run, I'd say dub in general should not process DRT options at all. Set the flag disabling the processing. Does this prevent people from profiling dub's GC usage? Yes. I'm not too concerned about it. Most of the time, they are going to send these options in expecting them to go to the program dub is running.

In fact, I just tried this:

`dub run -- --DRT-gcopt=profile:1`, and guess what? I get a profile! But it's of dub, not the actual program. That's incredibly confusing! Imagine the user's frustration thinking their GC usage in their application is incorrect, and nothing they try makes any difference.

We should just do what the user expects. It shouldn't be that controversial.

**Comment by schveiguy** [comment] 2019-12-23 05:20
And dub can also add in options to enable the GC profiling, or doing any other of the things that are useful for DRT options. It's worth the extra processing and effort to have a tool that works as expected.

**Comment by Geod24** [comment] 2019-12-23 05:38
> It just feels wrong to have no way to instruct the parameters to druntime without also limiting the processing on the main program. If I want the program to receive the options " --DRT-gcopt=profile:1 -- --anotherThing", how do I do it?

I *think* you imply that `--` would be consumed by druntime, right ? That's not what I intended. So if you want `--anotherThing` to be interpreted as option and `--DRT-gcopt=profile:1` to be interpreted as simple text, you pass `./myprogram --anotherThing -- --DRT-gcopt=profile:1`, and that's exactly what the program will receive (`args[] == [ "myprogram", "--anotherThing", "--", "--DRT-gcopt=profile:1"]`).
Then passing this to `getopt` would just work out of the box (which is the point).

> In fact, I just tried this: [...]

I mean, that's the [original report](https://github.com/dlang/dub/issues/1280#issue-270717778) I made, so I'm 100% with you here.
But you *did* instinctively position `--DRT-gcopt=profile:1` after the `--`, not before. Wouldn't `dub --DRT-gcopt=profile:1 run mypkg -- pkgarg` be confusing ?

> And dub can also add in options to enable the GC profiling

That's bound to lag behind any druntime option. Plus, certain (most?) options are not available once you reach `main`. I originally tried to disable RT option parsing and do it from `main`, but things like GC instantiation, configuration, or `oncycle` happens before the `main` is reacher.

**Comment by schveiguy** [comment] 2019-12-23 16:15
> I _think_ you imply that `--` would be consumed by druntime, right ? That's not what I intended. So if you want `--anotherThing` to be interpreted as option and `--DRT-gcopt=profile:1` to be interpreted as simple text

No, I meant the opposite. I want the program to receive the parameters `--DRT-gcopt=profile:1 -- --anotherThing`. Essentially the program is saying "I will handle DRT-gcopt", and also has a mechanism to treat further options as pass-through.

With the proposal you are saying the -- affects the DRT options, but is not removed from the options list, meaning it will affect the program as well.

> Wouldn't `dub --DRT-gcopt=profile:1 run mypkg -- pkgarg` be confusing

Assuming dub ignores all `--DRT` options, That would fail to run for an "invalid option" error.

> That's bound to lag behind any druntime option. Plus, certain (most?) options are not available once you reach `main`

Possibly. But again, there is pretty much non-existent demand to run GC profiling for the dub tool itself. 

I believe you can turn on profile for the GC at any time. As far as changing which GC you want to use, that is available as long as you do not allocate anything before switching. The cycle detection mechanism cannot be modified except via DRT options, but again, doing that specifically for dub probably has 0% demand.

**Comment by Geod24** [comment] 2019-12-24 02:29
> Essentially the program is saying "I will handle DRT-gcopt", and also has a mechanism to treat further options as pass-through.

Then the program should completely disable Druntime option processing. Do we currently have programs that want to handle `--DRT` options themselves ? I don't know any, but any program that spawns a D program suffers from the inability to pass down `--DRT` options.

> With the proposal you are saying the -- affects the DRT options, but is not removed from the options list, meaning it will affect the program as well.

Yes, that's what I meant by "consumed" by DRuntime. It affects druntime, but druntime does not consume it (it passes it to the program).

> Possibly. But again, there is pretty much non-existent demand to run GC profiling for the dub tool itself.

It's not only about GC profiling, but also runtime configuration in general.
And I disagree there is a non-existent demand for GC configuration. I mean, we [have an active issue about it](https://github.com/dlang/dub/issues/1812).

> I believe you can turn on profile for the GC at any time. As far as changing which GC you want to use, that is available as long as you do not allocate anything before switching. The cycle detection mechanism cannot be modified except via DRT options, but again, doing that specifically for dub probably has 0% demand.

AFAIK it's not something we test for, so it might break between releases.
Come to think of it, perhaps providing a C main and doing the runtime initialization oneself might work ?

In any case, you might want to move this discussion to https://github.com/dlang/druntime/pull/2881 since this is not only about `dub`.

**Comment by Geod24** [comment] 2022-09-13 03:33
Fixed upstream: https://github.com/dlang/druntime/pull/3628 .

**Closed by Geod24** 2022-09-13 03:33 UTC
