### ISSUE TITLE
I want move dub.selections.json to .dub/selections.json

### ISSUE THREAD

**Issue by zoujiaqing** [dlang/dub#1863] opened 2020-01-21 03:43 UTC
How to change it?

**Comment by Geod24** [comment] 2020-01-21 04:00
It is not possible, because `.dub` is not a folder users (should) need to interact with, while `dub.selections.json` is. Why do you need this ?

**Comment by zoujiaqing** [comment] 2020-01-21 10:55
When I input command `rm -rf ` and press `TAB` ... I want remove `dub.selections.json` but , often delete dub.json files by mistake :(

**Comment by Geod24** [comment] 2020-01-21 19:06
You shouldn't need to remove `dub.selections.json`, or at least it should be very rare.

> So why not put it together?

As mentioned above: `.dub` is not a directly users should directly interact with. It's "dub internal folder" and messing with it is not a good idea (just like you almost never touch `.git`). So the default `.gitignore` adds `dub.selections.json` to its list of ignored files.

On the other hand, users routinely commit their `dub.selections.json` to their repository. It is necessary if you want your build to be reproducible, e.g. in a CI environment, or months after the commit. That's why it lives at the root, alongside the manifest file.

**Comment by zoujiaqing** [comment] 2020-01-22 05:08
Thank you @Geod24 :)
This has nothing to do with git, I just don't like to see a lot of temporary files under the directory, which looks messy.

**Comment by Geod24** [comment] 2020-01-22 09:14
`dub.selections.json` is not intended as a temporary file. Currently we generate it for libraries as well, but that should probably be fixed, see https://github.com/dlang/dub/issues/1245
Hope this answers your question. Since it is not an issue, I'll close as WONTFIX.

**Closed** 2020-01-22 19:58 UTC
Labels: question, wontfix

**Comment by PetarKirov** [comment] 2020-01-22 20:05
@zoujiaqing here's some of many articles explaining why `package-lock.json` / `yarn.lock` (which are the analogs of `dub.selections.json` in the npm world) should be committed in version control:

* https://stackoverflow.com/a/44904494
* https://stackoverflow.com/a/44210813

**Comment by FeepingCreature** [comment] 2020-05-18 13:18
`git clean -ffixd` cleans up everything but committed files, but asks you first.
