### ISSUE TITLE
how to build only dependencies?

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#1076] opened 2017-02-19 03:19 UTC
is there a way to build only dependencies of a `dub.json`?
```
{
// other flags
"dependencies": {
dep1,
dep2,
}
}
```

**Comment by s-ludwig** [comment] 2017-02-19 20:55
I don't think it can be achieved right now. But there is a plan to make this work if the main package has `targetType "none"`, so then a possible way would be to add a special configuration that sets the target type appropriately and then build that (See #97)..

**Comment by WebFreak001** [comment] 2023-02-17 00:49
duplicate of #97

fixed in #1364

**Closed by WebFreak001** 2023-02-17 00:49 UTC
