### ISSUE TITLE
dub fetch and build in one command

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#946] opened 2016-09-29 16:50 UTC
dub install foo says install is deprecated.
Most package managers (homebrew, apt-get, macports etc) by default do fetch and build in 1 command.
how about making `dub install` do that (and not be deprecated)

**Comment by andre2007** [comment] 2019-08-19 15:38
Duplicate of https://github.com/dlang/dub/issues/839

**Closed by andre2007** 2019-08-19 15:38 UTC
