### ISSUE TITLE
Use the selected default compiler

### ISSUE THREAD

**Issue by AlexanderZhirov** [dlang/dub#2248] opened 2022-05-11 10:15 UTC
OS Solus Linux 4.3
DUB version 1.27.0, built on Apr 13 2022
LDC - the LLVM D compiler (1.29.0)

I am trying to use the default compiler in my project, referring to this [manual](https://dub.pm/settings):

```sh
$ROOT_PACKAGE_DIR/dub.settings.json
```

I want to use the `ldc2` compiler by default, without adding the `--compiler` key. For some reason, `dub` still refers to `dmd`.

**Comment by Geod24** [comment] 2022-07-27 23:19
What does your `dub.settings.json` looks like ?
It should be at least:
```json
{
    "defaultCompiler": "ldc2"
}
```

This work fine from my experience.

**Comment by Geod24** [comment] 2023-12-28 22:58
Closing as this works for me and there was no feedback. If you can reproduce, feel free to re-open.

**Closed by Geod24** 2023-12-28 22:58 UTC
