### ISSUE TITLE
dub generate visuald is limited to one build

### ISSUE THREAD

**Issue by Flamaros** [dlang/dub#445] opened 2014-10-26 10:12 UTC
It would be nice if we could generate a VisualD solution with many build configurations.

With something like :
dub generate visuald --build="debug,release"

**Comment by AndreyMZ** [comment] 2015-06-20 10:01
+1
I agree with p0nce, but his solution is a future.
For now I would like to have Flamaros's solution. It should be easy...

**Comment by WebFreak001** [comment] 2023-02-16 19:50
duplicate of #264

**Closed as completed by WebFreak001** 2023-02-16 19:50 UTC
Labels: duplicate
