### ISSUE TITLE
Unused configuration dependencies still evaluated

### ISSUE THREAD

**Issue by rjmcguire** [dlang/dub#904] opened 2016-07-26 12:59 UTC
When I try compile a project that depends on a project with the below configurations the "api-server" "onyx-config" dependency is still evaluated and is shown as missing. If I remove the configuration "api-server" then my project that depends on this library compiles fine. Would be great if dub could just avoid evaluating the unused configuration.

```sdlang
configuration "default" {
    targetType "library"
    excludedSourceFiles "source/main.d" "source/config.d"
}
configuration "api-server" {
    targetType "executable"
    dependency "onyx-config" path="onyx-config-2.0.3"
}
```

**Comment by ghost91-** [comment] 2018-05-03 19:03
In my opinion, this is a really big problem, because it also applies to dependencies. For example, if my project has `requests` as dependency (with the default configuration, which is called `std` in this case), it will still pull completely pull in `vibe.d`, because `requests` also has a configuration, which has `vibe.d` as a dependency. Granted, it will not be compiled in, but even downloading is not neccessary.

This is a big problem in memory constrained areas. And just today while talking to somebody at dcond, I found out that it also prevents wider adoption of D by businesses because it creates problems with compliance processes and so on (you have to check all downloaded dependencies, even if they are not used...).

#1148 Seems to be a bit related to this, but I think it is still a different issue. Does anybody have an idea how to tackle this?

**Comment by ghost91-** [comment] 2018-05-03 21:34
I just found another annoying problem with this: If a dependency of your package hard dependes (`==`) on a certain version of another package in one of its configurations and your package also depends on that same dependency, but in a version that is not compatible (e.g. a newer one), the dependencies can not be satisfied.

The concrete example is the following: My project depends on `mysql-native` which has the dependency
```dependency "unit-threaded" version="==0.7.37"```
in its `unittest-vibe-ut` configuration. My project also depends on `unit-threaded` and I would like to upgrade it to more recent versions (the most recent one is 0.7.45). However, this is not possible, because even though the `unittest-vibe-ut` configuration of `mysql-native` is never actually built, it still gets considered for dependency resolution.

**Comment by Geod24** [comment] 2020-01-02 04:24
Duplicate of https://github.com/dlang/dub/issues/1706

Well, really, #1706 is the duplicate, but it also has more discussions, so this issue instead.

**Closed by Geod24** 2020-01-02 04:24 UTC
Labels: duplicate
