### ISSUE TITLE
dub --nodeps not working when --compiler is used:

### ISSUE THREAD

**Issue by SrMordred** [dlang/dub#1009] opened 2016-12-06 00:46 UTC
Works properly (avoiding package check/update)
`dub run --nodeps`

Checks for package update.
`dub run --nodeps --compiler=ldc2`

**Comment by s-ludwig** [comment] 2016-12-19 00:48
Can't reproduce, `--nodeps` skips the upgrade check in both cases for me. Since the flag is handled independently of all other flags, it is unlikely to be directly related to the `--compiler` switch. Can you verify that the two cases above behave like that consistently for you?

**Comment by SrMordred** [comment] 2016-12-19 01:00
Iep, i was just seeing this behavior right now.
Im on Windows 10 , dub 1.1.1

**Comment by s-ludwig** [comment] 2016-12-19 01:01
Can you post the output of the two commands with `-v` added? I'll re-test on Windows when I get the change (my test was on Linux).

**Comment by SrMordred** [comment] 2016-12-19 01:12
Both are identical, except that the dmd version skip one step all libs and the ldc2 version pass slow through each.

```
D:\game>dub run --nodeps --arch=x86_64 --compiler=dmd -v
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\this_\AppData\Roaming\dub\packages\local-packages.json
Determined package version using GIT: game ~master
Refreshing local packages (refresh existing: false)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\this_\AppData\Roaming\dub\packages\local-packages.json
  Found dependency derelict-sdl2 2.0.2
    Found dependency derelict-util 2.0.6
  Found dependency gl3n 1.3.1
  Found dependency derelict-gl3 1.0.19
  Found dependency derelict-lua 1.3.0
Generating using build
Generate target game (executable D:\game game)
Generate target derelict-gl3 (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\lib DerelictGL3)
Generate target derelict-util (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\lib DerelictUtil)
Generate target derelict-lua (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\lib DerelictLua)
Generate target derelict-sdl2 (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\lib DerelictSDL2)
Generate target gl3n (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n gl3n)
Performing "debug" build using dmd for x86_64.
derelict-util 2.0.6: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\.dub\build\library-debug-windows-x86_64-dmd_2072-C4216C5D5611677879358614E2497068\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\.dub\build\library-debug-windows-x86_64-dmd_2072-C4216C5D5611677879358614E2497068\DerelictUtil.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\lib
derelict-gl3 1.0.19: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\.dub\build\library-debug-windows-x86_64-dmd_2072-6F8B2329BDA2DC124F5E3333E0504DCB\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\.dub\build\library-debug-windows-x86_64-dmd_2072-6F8B2329BDA2DC124F5E3333E0504DCB\DerelictGL3.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\lib
derelict-lua 1.3.0: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\.dub\build\library-debug-windows-x86_64-dmd_2072-FA690CD37CF4D5264726CE25311B1B41\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\.dub\build\library-debug-windows-x86_64-dmd_2072-FA690CD37CF4D5264726CE25311B1B41\DerelictLua.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\lib
derelict-sdl2 2.0.2: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\.dub\build\library-debug-windows-x86_64-dmd_2072-B2A796BDB3D4946FE616DA05E2F91DB5\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\.dub\build\library-debug-windows-x86_64-dmd_2072-B2A796BDB3D4946FE616DA05E2F91DB5\DerelictSDL2.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\lib
gl3n 1.3.1: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n\.dub\build\library-debug-windows-x86_64-dmd_2072-626B771ADD21BA5C9B1D6C0053BBD7C8\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n\.dub\build\library-debug-windows-x86_64-dmd_2072-626B771ADD21BA5C9B1D6C0053BBD7C8\gl3n.lib to C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n
game ~master: target for configuration "application" is up to date.
Using existing build in D:\game\.dub\build\application-debug-windows-x86_64-dmd_2072-8072BE8412A44F7CB38F1AF02CA25701\.
Copying target from D:\game\.dub\build\application-debug-windows-x86_64-dmd_2072-8072BE8412A44F7CB38F1AF02CA25701\game.exe to D:\game
To force a rebuild of up-to-date targets, run again with --force.
Running .\game.exe


D:\game>dub run --nodeps --arch=x86_64 --compiler=ldc2 -v
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\this_\AppData\Roaming\dub\packages\local-packages.json
Determined package version using GIT: game ~master
Refreshing local packages (refresh existing: false)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\this_\AppData\Roaming\dub\packages\local-packages.json
  Found dependency derelict-sdl2 2.0.2
    Found dependency derelict-util 2.0.6
  Found dependency gl3n 1.3.1
  Found dependency derelict-gl3 1.0.19
  Found dependency derelict-lua 1.3.0
Generating using build
Generate target game (executable D:\game game)
Generate target derelict-gl3 (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\lib DerelictGL3)
Generate target derelict-util (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\lib DerelictUtil)
Generate target derelict-lua (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\lib DerelictLua)
Generate target derelict-sdl2 (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\lib DerelictSDL2)
Generate target gl3n (staticLibrary C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n gl3n)
Performing "debug" build using ldc2 for x86_64.
derelict-util 2.0.6: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\.dub\build\library-debug-windows-x86_64-ldc_2071-23EF40EA5745B453D9AF6413751E939C\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\.dub\build\library-debug-windows-x86_64-ldc_2071-23EF40EA5745B453D9AF6413751E939C\DerelictUtil.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\lib
derelict-gl3 1.0.19: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\.dub\build\library-debug-windows-x86_64-ldc_2071-7B4F380C36BE6D9D395075BB4453E2DC\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\.dub\build\library-debug-windows-x86_64-ldc_2071-7B4F380C36BE6D9D395075BB4453E2DC\DerelictGL3.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-gl3-1.0.19\derelict-gl3\lib
derelict-lua 1.3.0: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\.dub\build\library-debug-windows-x86_64-ldc_2071-1794DEECB484C29615F80F40E923C619\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\.dub\build\library-debug-windows-x86_64-ldc_2071-1794DEECB484C29615F80F40E923C619\DerelictLua.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-lua-1.3.0\derelict-lua\lib
derelict-sdl2 2.0.2: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\.dub\build\library-debug-windows-x86_64-ldc_2071-4485BE11E8111A715DB6EA9A33272745\.
Copying target from C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\.dub\build\library-debug-windows-x86_64-ldc_2071-4485BE11E8111A715DB6EA9A33272745\DerelictSDL2.lib to C:\Users\this_\AppData\Roaming\dub\packages\derelict-sdl2-2.0.2\derelict-sdl2\lib
gl3n 1.3.1: target for configuration "library" is up to date.
Using existing build in C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n\.dub\build\library-debug-windows-x86_64-ldc_2071-1C8F034BEC13027C677D9A6FC0B9F388\.
                                                                         Copying target from C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n\.dub\build\library-debug-windows-x86_64-ldc_2071-1C8F034BEC13027C677D9A6FC0B9F388\gl3n.lib to C:\Users\this_\AppData\Roaming\dub\packages\gl3n-1.3.1\gl3n
game ~master: target for configuration "application" is up to date.
Using existing build in D:\game\.dub\build\application-debug-windows-x86_64-ldc_2071-1D399259020A2D0F9B2BABF131A665D8\.
Copying target from D:\game\.dub\build\application-debug-windows-x86_64-ldc_2071-1D399259020A2D0F9B2BABF131A665D8\game.exe to D:\game
To force a rebuild of up-to-date targets, run again with --force.
Running .\game.exe
```

**Comment by s-ludwig** [comment] 2016-12-19 01:27
Okay, then it looks like this isn't really related to `--nodeps`, but the slowdown comes from somewhere else. As a shot in the dark, it may be the compilation of the platform probe, where LDC might have more startup overhead. However, on Linux I'm just seeing a slowdown of 15msecs  for LDC, Windows may be worse.

**Comment by WebFreak001** [comment] 2023-02-17 02:02
closing as unreproducible, on windows these kind of delays can occur due to anti virus programs like windows defender.

**Closed by WebFreak001** 2023-02-17 02:02 UTC
