### ISSUE TITLE
Add a global configuration option for the default compiler/architecture

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#383] opened 2014-07-24 15:25 UTC
Right now, using any specific compiler or architecture requires passing explicit `--compiler`/`--arch` flags to DUB. In many cases it would be desirable to just override the default instead.

See also http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/1948/

**Comment by greenify** [comment] 2016-04-07 16:26
related to #557

**Comment by wilzbach** [comment] 2017-09-13 01:24
Closing as a duplicate of#501

**Closed by wilzbach** 2017-09-13 01:24 UTC
Labels: enhancement

**Comment by s-ludwig** [comment] 2017-09-13 11:03
#501 is about a "dub docs" command and #557 and #590 talk about different configuration fields (the configuration file itself is already there). It may make sense to keep them open, but to adjust their titles to better reflect the fields that they propose.
