### ISSUE TITLE
Support nonet application

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub#1923] opened 2020-04-15 11:08 UTC
Currently there might be issues in the library-nonet implementation like in #1910 which are not caught by the simple unittests. Running the full tests directory on a dub executable using library-nonet (vibe.d instead of curl) would prevent such issues from happening much better.

**Comment by gedaiu** [comment] 2020-04-15 12:30
Can you give me an idea about what is needed to change here? I looked at the ci scripts and they look quite complex.

**Comment by Geod24** [comment] 2020-04-15 12:38
Duplicate of https://github.com/dlang/dub/issues/1558 ?

**Comment by WebFreak001** [comment] 2020-04-15 12:41
no this is an issue about adding some travis config and a new dub configuration like application-nonet because there is no `targetType "executable"` with nonet (no curl) in the dub.json

#1558 is about using dub as a library with nonet config, but it will most likely also fix the compilation issues in there if this is fixed.

**Comment by WebFreak001** [comment] 2020-04-15 12:42
@gedaiu a configuration for application-nonet would need to be added and in dub.json and then built using the previously built dub (or manually adjust the build script but I think this is rather error-prone)

In the end it you would just change the scripts/ci/travis.sh where it runs test/run-unittest.sh to run it with the DUB environment variable pointing to the nonet application

**Comment by gedaiu** [comment] 2020-04-15 12:46
I see, so in the end you want to test this configuration in the existing travis jobs. It should be easy to change..

What about `semaphore-ci.sh` ? 
Should this be changed too?

**Comment by Geod24** [comment] 2022-10-28 12:46
Fixed by https://github.com/dlang/dub/pull/2509

**Closed by Geod24** 2022-10-28 12:46 UTC

**Comment by WebFreak001** [comment] 2022-10-28 13:24
for the use-case of not needing curl, continued here: #2512
