### ISSUE TITLE
Dub with inexistent dependency on other configuration

### ISSUE THREAD

**Issue by MrcSnm** [dlang/dub#2627] opened 2023-04-01 00:00 UTC
### System information

- **dub version**: 1.31.0
- **OS Platform and distribution**: Any
- **compiler version** 2.102

### Bug Description

Basically, this will fail when build with the default configuration.  But the non existent dependency in the other config is not required for the default configuration and thus, should build.
I know that there exists optional, but optional seems to have a little different use case than handling that. I want to know if you guys are willing to keep it like that and I must really use optional or if that is a bug.

### How to reproduce?

```json
{
	"authors": [
		"Marcelo Silva"
	],
	"copyright": "Copyright © 2023, Marcelo Silva",
	"description": "A minimal D application.",
    "configurations": [
        {
            "name": "default"
        },
        {
            "name": "withDeps",
            "dependencies": {
                "noExist": {"path": "../"}
            }
        }
    ],
	"license": "proprietary",
	"name": "inexistent_ddep"
}
```

**Comment by WebFreak001** [comment] 2023-04-01 07:00
see #1217 for that dependency resolution should fail right now. Building should theoretically be fine though, so we can maybe adjust the building / dependency fetching algorithm to only fetch dependencies that are needed for the build configuration.

**Comment by Geod24** [comment] 2024-01-17 23:07
As mentioned, it's a duplicate of a well known issue (which is even pinned in this repository). I am working on it.

**Closed by Geod24** 2024-01-17 23:07 UTC
Labels: duplicate
