### ISSUE TITLE
cache local ist broken

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1180] opened 2017-06-30 14:50 UTC
--cache local is not working. 

```
dub init vibetest -t vibe.d
cd vibetest
dub build --cache local
```

C:\Users\user\Desktop\vibetest>dub build --cache local
Fetching libevent 2.0.2+2.0.16 (getting selected version)...
Fetching diet-ng 1.2.1 (getting selected version)...
Fetching openssl 1.1.5+1.0.1g (getting selected version)...
Fetching memutils 0.4.9 (getting selected version)...
Fetching vibe-d 0.7.31 (getting selected version)...
Fetching libasync 0.8.3 (getting selected version)...
Non-optional dependency vibe-d of vibetest not found in dependency tree!?.

**Comment by atilaneves** [comment] 2018-01-12 11:27
I ran into this today. It works if you `dub fetch $PACKAGE --cache=local` first. The issue is that the behaviour is different from the default - then it does a dub fetch for you. It should do the same with `--cache=local`.

**Comment by andre2007** [comment] 2018-09-23 20:16
@wilzbach @WebFreak001 
With --cache=local the dependeny is stored in the package root directory but not added to dub.json nor found by the dependency collector. The dependency collector looks only in the user and system path. I wonder whether this is by purpose? 
Should the dependency collector also look into the package path?

**Comment by andre2007** [comment] 2018-09-24 15:45
Pull request https://github.com/dlang/dub/pull/1568

**Comment by Geod24** [comment] 2019-12-21 08:01
PR merged.

**Closed by Geod24** 2019-12-21 08:01 UTC
