### ISSUE TITLE
not getting PIC for shared library

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub#613] opened 2015-06-30 10:27 UTC
on ubuntu 15.04 x86_64

A simple 1-file project with `"targetType": "dynamicLibrary"` doesn't get compiled with -fPIC

The compile step, as reported by `dub -v build` is
`dmd -c -of.dub/build/library-debug-linux.posix-x86_64-dmd_2067-FA32B08D9C0006B2A066E7CC872D6501/ppyd.o -debug -g -w -version=Have_ppyd ppyd.d`

**Comment by John-Colvin** [comment] 2015-06-30 10:28
I notice this has been reported and fixed once before. Is it in the test suite?

**Comment by John-Colvin** [comment] 2015-06-30 10:32
tested with dub 0.9.23 and git HEAD

**Comment by p0nce** [comment] 2015-07-26 11:57
Hitting this too.

**Comment by s-ludwig** [comment] 2015-07-26 13:15
Okay, sneaked the fix in before release ;) Would be good if someone could test if this also fixes more complex scenarios, I just tested building a `dynamicLibrary` package directly, but not as a dependency for example.

**Comment by p0nce** [comment] 2015-07-26 21:16
I fix this isn't fixed indeed.

It have a non-trivial scenario here: https://github.com/p0nce/dplug/blob/master/examples/distort/dub.json

In non-combined here is the `dub -v -f`  output: http://pastebin.com/BRgv7NXH
It **does** compile in --combined. 

System: DUB master, DMD 2.067.1, Ubuntu

My understanding is that `-fPIC` is a code generation flag that should be applied to anything that goes in a shared library. In the DUB log, static libraries dependencies are not compiled with `-fPIC` which I believe is the problem.

**Comment by s-ludwig** [comment] 2015-07-27 11:22
Ah, right, didn't think of that. This will require some deeper changes, because the static library files will have to get a different hash value in the build cache folder. It will probably also mean that if the same static library is used for both, a dynamic library and an executable, the PIC version will also be used for the executable, even if that isn't ideal. I don't think it will be possible to map that to other build systems otherwise.

**Comment by p0nce** [comment] 2015-07-27 12:02
Unfortunately because of DMD codegen bugs, I tend to rely on sub-packages with {optimization | inlining} disabled so `--combined` is less than ideal (though maybe 2.068-b2 brings an end to this).

>  It will probably also mean that if the same static library is used for both, a dynamic library and an executable, the PIC version will also be used for the executable, even if that isn't ideal.

Sorry I don't understand this sentence, does this happen even if such builds get different hash values?

.

**Comment by s-ludwig** [comment] 2015-07-27 12:10
>> It will probably also mean that if the same static library is used for both, a dynamic library and an executable, the PIC version will also be used for the executable, even if that isn't ideal.

> Sorry I don't understand this sentence, does this happen even if such builds get different hash values?

The problem is that each package corresponds (at most) to a single binary target during a single build. Think of a VisualStudio solution where you'd just be able to insert each project once and would have to decide for each if it should be built with or without -fPIC. So if the same static library package is referenced both by a dynamic library and an executable within the same dependency graph, it will be necessary to generally enable -fPIC for it.

Now it would be possible to work around that, especially within DUB's own builder, but I'm not sure how good that idea would generally be.

**Comment by p0nce** [comment] 2015-07-27 12:17
OK I see. I found it strange because in my DUB use cases only the top-level project is possibly an executable or a shared library, everything else is source library.

**Comment by wilzbach** [comment] 2018-05-11 13:25
-fPIC has been DMD's default since 2.072 for 64-bit builds.
@p0nce is this still an issue for you?

**Comment by John-Colvin** [comment] 2018-05-11 13:30
I'm pretty sure the bug this was re-opened for was resolved [here](https://github.com/dlang/dub/pull/972)

**Comment by wilzbach** [comment] 2018-05-11 13:46
Cool. Closing then. @p0nce feel free to reopen if this is incorrect

**Closed by wilzbach** 2018-05-11 13:46 UTC

**Comment by p0nce** [comment] 2018-05-11 21:39
@wilzbach , definately no problem here :)
