### ISSUE TITLE
Couldn't resolve host name on handle

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#928] opened 2016-09-13 01:40 UTC
```
dub fetch mir --version=0.17.0-alpha2
Fetching mir 0.17.0-alpha2...
Couldn't resolve host name on handle 1EAE6D0
```

**Comment by dhasenan** [comment] 2017-09-16 16:42
Can't reproduce on linux64 with latest dub. Is this error still occurring? If so, can you provide more info on the environment you used to produce this error?

**Comment by MartinNowak** [comment] 2017-09-18 17:02
That's a temporary curl name resolving error, we've added more verbose error output for request errors recently.
https://github.com/dlang/dub/pull/1104

**Closed by MartinNowak** 2017-09-18 17:02 UTC
