### ISSUE TITLE
changing working dir with `--root` breaks building with path dependency

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub#670] opened 2015-09-08 13:19 UTC
Not exactly sure yet what the problem is, but some dependencies cannot be resolved when building vibe.d's examples using `dub --root=examples/auth_basic build`.
If not already done `dub --root` should translate to an initial `chdir` to avoid having to account for a different root path throughout the source code.

**Comment by MartinNowak** [comment] 2015-09-08 13:35
Apparantly the CWD is used to run a command with different `--root` so we'd need another chdir before running.

**Comment by s-ludwig** [comment] 2015-09-14 14:12
Couldn't reproduce this on master (Windows). I've tried to run the command above from a directory that was not registered using add-local/add-path and without any cached dependencies installed. It downloaded all dependencies (oddly also the latest release version of vibe.d) and then built without error.

`--root` generally doesn't issue a `chdir`, but uses the supplied root path as the base to convert all accesses to the root package to use absolute paths.

**Comment by Geod24** [comment] 2019-12-27 01:49
> Apparantly the CWD is used to run a command with different `--root` so we'd need another chdir before running.

That would be a duplicate of https://github.com/dlang/dub/issues/384 then

**Closed by Geod24** 2019-12-27 01:49 UTC
Labels: duplicate
