### ISSUE TITLE
Build failed with ldc-win64-msvc compilers - unknown .a extension

### ISSUE THREAD

**Issue by buggins** [dlang/dub#835] opened 2016-05-04 07:07 UTC
For Windows builds using LDC with msvc linker, static libraries must have extension .lib instead of .a

How to reproduce:
in any dub project which uses some static library dub dependency, try to build it with ldc2 or ldmd2:
dub build --compiler=C:\Tools\D\ldc2-1.0.0-beta1-win64-msvc\bin\ldmd2.exe
You will get "Error: unrecognized file extension a"

Solution: if "win64-msvc" is found in compiler binary path, use .lib instead of .a for static lib names.

**Comment by p0nce** [comment] 2016-05-16 17:27
I rename the LDC directory to something else, this wouldn't work.

**Comment by jmh530** [comment] 2017-06-28 21:05
This is likely eligible to close based on the ldc issue saying it was fixed in dub 1.1.1.

**Comment by s-ludwig** [comment] 2017-06-28 21:17
True, this is a duplicate of #618, which has been solved.

**Closed by s-ludwig** 2017-06-28 21:17 UTC
