### ISSUE TITLE
dub init freezes dub and visual studio  2019 package manager

### ISSUE THREAD

**Issue by Shadowblitz16** [dlang/dub#1786] opened 2019-10-21 19:40 UTC
### System information
- **dub version**: 1.17.0
- **OS Platform and distribution**: Windows 7 Ultimate 64 bit
- **compiler version** v2.088.1-dirty

### Bug Description
Hello, I am using Visual D in visual studio 2019 community and I tried using the packages manager to run "dub add dsfml" however that froze the package manager and I had to go into task manager and force end the dub process.

### How to reproduce?
- create visual D project in visual studio 2019 community via new project dialog.
- open the package manager View->Other Windows->Package Manager Console
- wait package manager console to start up
- type `dub init`

### Expected Behavior
it runs correctly like if it were ran on windows console.

### Logs
_I would post them but I'm not sure where they are stored._

**Comment by andre2007** [comment] 2019-10-21 19:53
If you execute ```dub init --vverbose``` do you see the output in Visual Studio?

**Comment by ZombineDev** [comment] 2019-10-22 09:58
By default `dub init` is interactive, so my guess is that it was just waiting for user input and that was perceived as "freezing". There may be a problem, with the output however. I'm not sure how the output is different between the traditional windows console and the one that's integrated into VS.

**Comment by Shadowblitz16** [comment] 2019-10-22 20:12
@andre2007 
```
PM> dub init --vverbose
dub.exe : Using dub registry url 'https://code.dlang.org/'
At line:1 char:4
+ dub <<<<  init --vverbose
    + CategoryInfo          : NotSpecified: (Using dub regis...ode.dlang.org/':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Refreshing local packages (refresh existing: true)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at C:\Users\shadowblitz16\AppData\Local\dub\packages\local-packages.json
No valid package found in current working directory: No package file found in C:\Users\shadowblitz16\Documents\Visual Studio 2019\Projects\D\Asteroids+\, expected one of dub.json/dub.sdl/package.json
```

@ZombineDev it does freeze but it seems to do it after printing the that error. I can't type anything else in afterwards

**Comment by andre2007** [comment] 2020-01-02 08:24
This might be a duplicate of https://github.com/dlang/dub/issues/1682#issuecomment-570113220

As proposed by @Geod24 could you test it with master?

**Comment by Shadowblitz16** [comment] 2020-01-02 20:40
maybe in the future. I no longer have D install on my pc after updating to windows 10 and currently don't have time to install in right now.

**Comment by Geod24** [comment] 2020-05-20 16:48
Closing as I'm 98% sure it's a duplicate of #1682

**Closed by Geod24** 2020-05-20 16:48 UTC
