### ISSUE TITLE
Dub fetching public package despite specifying "path=" instead of "version=" (so, ignoring path)

### ISSUE THREAD

**Issue by AlexFolland** [dlang/dub#1088] opened 2017-02-28 05:58 UTC
I have this at the beginning of my program:

```
#!/usr/bin/env dub
/+ dub.sdl:
	name "bujutimer"
	description "A simple GUI timer and stopwatch."
	authors "Alex Folland"
	license "CC0"
	lflags "libui.lib"
	dependency "derelict-libui" path="DerelictLibui"
+/
```

When I run `dub build bujutimer.d --single --arch=x86_64 --parallel --force --compiler=ldc2`, I see this:

```
E:\media\projects\d\bujutimer>dub build bujutimer.d --single --arch=x86_64 --parallel --force --compiler=ldc2
Fetching derelict-libui 0.3.0 (getting selected version)...
Performing "debug" build using ldc2 for x86_64.
derelict-util 2.1.0: building configuration "library"...
Using Visual C++: C:\tools\visual studio 2015\VC
derelict-libui 0.3.0: building configuration "lib"...
Using Visual C++: C:\tools\visual studio 2015\VC
bujutimer ~master: building configuration "application"...
Using Visual C++: C:\tools\visual studio 2015\VC
```

This is incorrect.  It should not be `Fetching derelict-libui 0.3.0 (getting selected version)...` as "0.3.0" is not any version I selected.  It should be using the path I specified.  I've tried `path="./DerelictLibui"` and `path=".\\DerelictLibui"` also.

**Comment by timotheecour** [comment] 2017-06-11 00:12
@s-ludwig also running into this issue, which is a blocker for me, eg when compiling:
```
  "dependencies": {
    "vibe-d": "~>0.7.30",
    "ggplotd": "~>1.1.3",
    "dcv": {"path": "path/to/dcv"},
    "mir": "~>1.1.0",
  },
```
the logs show:
```
Downloading metadata for dcv
Getting from http://code.dlang.org/packages/dcv.json
Getting http://code.dlang.org/packages/dcv.json...
Ignoring version specification (>=0.0.0) for path based dependency ../../
Ignoring version specification (>=0.0.0) for path based dependency ../../
Return for dcv: [0.2.0+commit.1.gad867e2, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, ~master, ~rs]
```
which seems wrong since i specified path for dcv

**Comment by Geod24** [comment] 2023-12-29 01:10
I assume this was a duplicate of https://github.com/dlang/dub/issues/1583
I just tested single-package files just to be sure, and I don't see any request to the registry.

**Closed by Geod24** 2023-12-29 01:10 UTC

**Comment by AlexFolland** [comment] 2023-12-29 05:24
I have tested this same project with dub version `1.34.0` and it did indeed use my locally-sourced path with the `path="DerelictLibui"` argument.  I can confirm this issue has since been resolved in dub.  Here is terminal output from my test.

```
[alex@alex-pc bujutimer]$ dub clean && dub build bujutimer.d --single --arch=x86_64 --parallel --force --compiler=ldc2
    Cleaning artifacts for package bujutimer at /home/alex/.dub/cache/bujutimer/~master
    Starting Performing "debug" build using ldc2 for x86_64.
    Building derelict-util 2.1.0: building configuration [library]
    Building derelict-libui 0.3.0+commit.9.ga384c78: building configuration [lib]
    Building bujutimer ~master: building configuration [application]
     Linking bujutimer
[alex@alex-pc bujutimer]$
```

**Comment by Geod24** [comment] 2023-12-29 11:35
Thanks for confirming!
