### ISSUE TITLE
Regression: [dependency-target] not being identified in windows

### ISSUE THREAD

**Issue by MrcSnm** [dlang/dub#2560] opened 2023-01-04 11:07 UTC
### System information

- **dub version**:  DUB version 1.31.0-beta.1, built on Jan  1 2023
- **OS Platform and distribution**: Windows 10
- **compiler version** dmd 2.102

### Bug Description
Dub is not reading  anything from `dependencies-windows`. If I move directx-d to "dependencies" instead of "dependencies-windows", bug is fixed

### How to reproduce?
```json
"configurations": [
		{
			"name": "default",
			"dependencies": {
				"bindbc-opengl": {"version": "~>1.0.0", "optional": true},
				"hipengine_api": {"path": "../../api"},
				"windowing" : {"path" : "../windowing"},
				"data" : {"path": "../data"},
				"image" : {"path": "../image"},
				"bind" : {"path": "../bind", "optional": true},
				"config": {"path": "../config"},
				"error": {"path": "../error"},
				"math": {"path": "../math"}
			},
			"dependencies-windows": {
				"directx-d": {"path": "../../dependencies/directx-d", "optional": true}
			},
			"versions": [
				"HipGL3",
				"GL_45",
				"GL_ARB",
				"HipGLUseVertexArray"
			]
		},
}
```

### Logs
```
import path[0] = modules\renderer\source
import path[1] = modules\bind\source
import path[2] = C:\Users\Hipreme\AppData\Local\dub\packages\bindbc-lua-0.5.1\bindbc-lua\source
import path[3] = C:\Users\Hipreme\AppData\Local\dub\packages\bindbc-loader-1.0.1\bindbc-loader\source
import path[4] = C:\Users\Hipreme\AppData\Local\dub\packages\bindbc-openal-1.0.0\bindbc-openal\source
import path[5] = C:\Users\Hipreme\AppData\Local\dub\packages\bindbc-opengl-1.0.3\bindbc-opengl\source
import path[6] = modules\error\source
import path[7] = modules\console\source
import path[8] = modules\config\source
import path[9] = modules\debugging\source
import path[10] = modules\util\source
import path[11] = modules\data\source
import path[12] = api\source
import path[13] = modules\image\source
import path[14] = C:\Users\Hipreme\AppData\Local\dub\packages\arsd-official-10.9.8\arsd-official
import path[15] = modules\math\source
import path[16] = modules\windowing\source
import path[17] = C:\D\dmd2\windows\bin\..\..\src\phobos
import path[18] = C:\D\dmd2\windows\bin\..\..\src\druntime\import
```

**Comment by rikkimax** [comment] 2023-01-04 11:20
After talking on Discord, it appears to be a duplicate key problem. Thoughts @Geod24?

**Comment by Geod24** [comment] 2023-01-04 17:19
`dependencies-windows` actually only meant `dependencies`, and dub was ignoring the platform suffix.
See https://github.com/dlang/dub/issues/1049

**Comment by MrcSnm** [comment] 2023-01-04 17:21
No error message. That same dub configuration was working on dub 1.28.0

**Comment by Geod24** [comment] 2023-12-28 17:25
Actually this is a duplicate of #615

**Closed by Geod24** 2023-12-28 17:25 UTC
