### ISSUE TITLE
https://code.dlang.org/ is not picking up new package versions

### ISSUE THREAD

**Issue by mw66** [dlang/dub#2381] opened 2022-08-13 17:38 UTC
e.g.

https://code.dlang.org/packages/rust_interop_d

still shows :  0.2.6 

while

https://github.com/yilabs/librust_interop
v0.2.7 Latest 
2 days ago

BTW, can dub (the client command line tool) directly check github version, and skip the code.dlang.org registry?

**Comment by WebFreak001** [comment] 2022-08-14 16:36
triggered manual update now

duplicate of https://github.com/dlang/dub-registry/issues/338

**Closed by WebFreak001** 2022-08-14 16:36 UTC
