### ISSUE TITLE
Push version infos during compilation

### ISSUE THREAD

**Issue by etcimon** [dlang/dub#437] opened 2014-10-10 15:02 UTC
I'm translating a large library from C++ and it makes use of these constants, defined in the ./configure script:

```
enum BOTAN_VERSION_MAJOR = 2;
enum BOTAN_VERSION_MINOR = 0;
enum BOTAN_VERSION_PATCH = 0;
enum BOTAN_VERSION_DATESTAMP = 20141030;
enum BOTAN_VERSION_RELEASE_TYPE = "unreleased";
enum BOTAN_VERSION_VC_REVISION = "123";
enum BOTAN_DISTRIBUTION_INFO = "unspecified";
```

I can't think of a way on top of my head, but I think these should be set automatically by dub using the version control information from the git repository, probably writing it into an auto-generated module with a specific name.

**Comment by MartinNowak** [comment] 2015-03-17 09:17
The pre/post build steps get some variable passed via env.
You could pass the semver too.
https://github.com/D-Programming-Language/dub/blob/1e81a9296ed807c4f73e4131619931fc6c655fc4/source/dub/generators/generator.d#L449

**Comment by s-ludwig** [comment] 2015-03-17 09:19
Related: #6

**Comment by s-ludwig** [comment] 2015-03-17 09:23
The downside of an automatically generated module is that this makes replicating the build process without DUB more difficult. But on the other hand, getting programmatic access to the current version of a project is a constant nuisance in my experience (using GIT based hacks or manually maintained version constants), so having a built-in solution would definitely be a very nice to have thing.

**Comment by Geod24** [comment] 2023-12-29 01:18
Duplicate of https://github.com/dlang/dub/issues/1438 (well, it precedes it, but 1438 has more conversation).

**Closed by Geod24** 2023-12-29 01:18 UTC

**Comment by etcimon** [comment] 2023-12-29 16:14
Imagine seeing an issue being replied to almost a decade later

**Comment by etcimon** [comment] 2023-12-29 16:16
Please don't let this one go stale https://github.com/dlang/dub/pull/2753
