### ISSUE TITLE
dub does not compile on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Mailaender** [dlang/dub#1141] opened 2017-06-03 11:44 UTC
```
[...]

[    9s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libphobos2.a(socket_1a96_452.o): relocation R_X86_64_32 against symbol `_D37TypeInfo_xE3std6socket13AddressFamily6__initZ' can not be used when making a shared object; recompile with -fPIC
[    9s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: final link failed: Nonrepresentable section on output
[    9s] collect2: error: ld returned 1 exit status
[    9s] Error: linker exited with status 1
```

I assume I have to add `"%{optflags} -fPIC"`, but I don't know where.

**Comment by BBasile** [comment] 2017-06-03 12:46
Perhaps
```js
"dflags" : ["-fPIC"],
```

**Comment by MartinNowak** [comment] 2017-06-14 07:50
Did OpenSUSE also switch to PIE by default? We've enabled `-fPIC` for X86_64 targets by default with 2.072.2.
Did you use the official dlang rpm installer?
Also please check your `/etc/dmd.conf` whether it contains `-fPIC` (see https://github.com/dlang/installer/blob/bd6e4c1e0a761acbd31851e42b84896ddd6ff31f/linux/dmd_rpm.sh#L255 for the change).

You can also easily test this with the install script, will download and extract dmd to `~/dlang`.
```sh
curl -fsS https://dlang.org/install.sh | bash -s dmd-2.074.1
source ~/dlang/dmd-2.074.1/activate
dub build --compiler=$DC
```

**Comment by okurz** [comment] 2017-06-16 20:56
to answer your question regarding openSUSE. Yes, the build switched to PIE by default :-)

**Comment by MartinNowak** [comment] 2017-06-17 02:31
@Mailaender how did you install dmd and which version are you using.
It should be configured to use `-fPIC` by default but apparently isn't.

**Comment by BBasile** [comment] 2017-06-17 02:36
@okurz: Leap not yet.

**Comment by okurz** [comment] 2017-06-17 06:34
openSUSE Tumbleweed switched to PIE, see https://lists.opensuse.org/opensuse-factory/2017-06/msg00403.html . The last released version of openSUSE Leap, openSUSE Leap 42.2 is as it looks like untouched as well as the version currently in Beta, openSUSE Leap 42.3. I branched the build project for dub+dmd+etc. within [OBS](https://build.opensuse.org/project/show/home:okurz:branches:devel:languages:D) to check how the situation looks like when building against openSUSE:Factory, openSUSE:Tumbleweed, openSUSE:Leap:42.2 and openSUSE:Leap:42.3 . openSUSE Leap 42.2+42.3 are all fine with the latest (released) version of dmd+dub but [openSUSE Tumbleweed](https://build.opensuse.org/project/monitor/home:okurz:branches:devel:languages:D?arch_x86_64=1&defaults=0&failed=1&repo_openSUSE_Tumbleweed=1) fails to compile [dmd](https://build.opensuse.org/package/live_build_log/home:okurz:branches:devel:languages:D/dmd/openSUSE_Tumbleweed/x86_64) with

```
[   33s] c++ -c -Wno-deprecated -Wstrict-aliasing -fno-exceptions -fno-rtti -D__pascal= -DMARS=1 -DTARGET_LINUX=1 -DDM_TARGET_CPU_X86=1 -m64 -std=gnu++98 -O2 -Iroot -MMD -MF newdelete.deps root/newdelete.c
[   34s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: idgen.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
[   34s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: final link failed: Nonrepresentable section on output
[   34s] collect2: error: ld returned 1 exit status
```

so I assume the problem is within dmd itself, how it's compiled, not dub.

**Comment by MartinNowak** [comment] 2017-07-05 11:47
> And if I try to patch "-fPIC" into the Makefile for building dmd I get a segfault so I assume this is not the way to go ;-) Help appreciated.

That's weird, let's take this issue to our Bugzilla @okurz.
[Issue 17598 – dmd fails to build on OpenSUSE Tumbleweed](https://issues.dlang.org/show_bug.cgi?id=17598).
Looks like the ldc bootstrap compiler you're using isn't configured for PIC/PIE by default (`[   68s] CC=c++ ldmd2 idgen.d`). Why are you using ldc to bootstrap?
Your problem seem to be fixed by https://github.com/ldc-developers/ldc/issues/1618/https://github.com/ldc-developers/ldc/pull/1664 which is in ldc 1.1.0.

**Comment by okurz** [comment] 2017-07-07 17:25
@MartinNowak I don't really know what I'm doing :-) I was mainly playing around with different things and hoping I could by accident end up with something that build and works after the recent breakage.

**Comment by Mailaender** [comment] 2017-07-08 09:01
I chose to build https://github.com/ldc-developers/ldc/releases/tag/v0.17.4 for bootstrapping purposes. Can we switch to the latest one now that https://build.opensuse.org/package/show/openSUSE:Factory/ldc is available? Those circular build dependency scenarios are always confusing for me and I don't know what is the best practice for them.

**Comment by GreatEmerald** [comment] 2017-07-28 18:51
One way to do it could be to bootstrap DMD with DMD... Have the VM install a static DMD RPM from the website and use that. Though that is a rather hacky method (but that's about how the AUTO_BOOTSTRAP method works).

**Comment by okurz** [comment] 2017-07-29 10:52
sure, I guess there is no problem to also use the open build service for that "hacky" approach - which I don't actually consider hacky, IMHO a valid bootstrapping approach.

**Comment by joakim-noah** [comment] 2017-09-05 19:20
Not a dub problem, but D compiler problem.

**Closed by joakim-noah** 2017-09-05 19:20 UTC
