### ISSUE TITLE
dub upgrade not working any longer (wget/curl?)

### ISSUE THREAD

**Issue by Timoses** [dlang/dub#1405] opened 2018-03-06 15:50 UTC
### System information

- **dub version**: 
```
> dub --version
DUB version 1.7.2-1, built on Feb 16 2018
```
- **OS Platform and distribution**: 
```
> uname -a
Linux xxx 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
```
- **compiler version**  irrelevant

### Bug Description
`dub upgrade` throws `HTTP request returned status code 0`.
E.g.
```
Package vibe-d not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
```
With dub version 1.6.0 it works.

### How to reproduce?
It might be because I am behind a company proxy.
https works with wget but not with curl.

Did dub change from wget to curl???

### Expected Behavior
Download with wget/curl whichever works

### Logs
Dub version 1.7.2-1:
```
> dub --version
DUB version 1.7.2-1, built on Feb 16 2018

> dub upgrade -v
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/timoses/.dub/packages/local-packages.json
Determined package version using GIT: kxml 1.0.1+commit.1.g337ff04
Determined package version using GIT: mescheka 0.0.6+commit.2.g6afba55
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/timoses/.dub/packages/local-packages.json
  Found dependency vibe-d 0.8.2
    Found dependency vibe-d:redis 0.8.2
      Found dependency vibe-d:http 0.8.2
        Found dependency vibe-d:tls 0.8.2
          Found dependency vibe-d:stream 0.8.2
            Found dependency vibe-d:core 0.8.2
              Found dependency vibe-d:utils 0.8.2
              Found dependency vibe-d:data 0.8.2
              Found dependency libevent 2.0.2+2.0.16
              Found dependency libasync 0.8.3
                Found dependency memutils 0.4.10
              Found dependency vibe-core 1.4.0-alpha.1
                Found dependency stdx-allocator 2.77.0
                Found dependency eventcore 0.8.28
                  Found dependency taggedalgebraic 0.10.9
          Found dependency openssl 1.1.6+1.0.1g
          Found dependency botan 1.12.9
            Found dependency botan-math 1.0.3
        Found dependency vibe-d:crypto 0.8.2
        Found dependency vibe-d:inet 0.8.2
          Found dependency vibe-d:textfilter 0.8.2
        Found dependency diet-ng 1.4.4
    Found dependency vibe-d:mongodb 0.8.2
    Found dependency vibe-d:web 0.8.2
    Found dependency vibe-d:mail 0.8.2
  Found dependency mescheka:telex 0.0.6+commit.2.g6afba55
    Found dependency mescheka:util 0.0.6+commit.2.g6afba55
    Found dependency mescheka:implant 0.0.6+commit.2.g6afba55
      Found dependency kxml >=0.0.0 @../../../../../../home/timoses/.dub/packages/kxml
Upgrading project in /media/sf_C_DRIVE/Users/funke_t1/Code/mescheka
Search for versions of vibe-d (1 package suppliers)
Package vibe-d not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for vibe-d: [0.8.2, 0.7.32, 0.8.3-alpha.4, 0.8.3-alpha.2, 0.8.2-rc.1]
Search for versions of stdx-allocator (1 package suppliers)
Package stdx-allocator not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for stdx-allocator: [2.77.0]
Search for versions of libevent (1 package suppliers)
Package libevent not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for libevent: [2.0.2+2.0.16]
Search for versions of libasync (1 package suppliers)
Package libasync not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for libasync: [0.8.3]
Search for versions of memutils (1 package suppliers)
Package memutils not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for memutils: [0.4.10, 0.4.9]
Search for versions of vibe-core (1 package suppliers)
Package vibe-core not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for vibe-core: [1.4.0-alpha.1, 1.3.0-rc.2]
Search for versions of eventcore (1 package suppliers)
Package eventcore not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for eventcore: [0.8.28, 0.8.27, 0.8.25]
Search for versions of taggedalgebraic (1 package suppliers)
Package taggedalgebraic not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for taggedalgebraic: [0.10.9, 0.10.7]
Search for versions of openssl (1 package suppliers)
Package openssl not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for openssl: [1.1.6+1.0.1g]
Search for versions of botan (1 package suppliers)
Package botan not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for botan: [1.12.9]
Search for versions of botan-math (1 package suppliers)
Package botan-math not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for botan-math: [1.0.3]
Search for versions of diet-ng (1 package suppliers)
Package diet-ng not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for diet-ng: [1.4.4, 1.4.3]
Search for versions of kxml (1 package suppliers)
Package kxml not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Return for kxml: [1.0.1+commit.1.g337ff04]
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/timoses/.dub/packages/local-packages.json
  Found dependency vibe-d 0.8.2
    Found dependency vibe-d:redis 0.8.2
      Found dependency vibe-d:http 0.8.2
        Found dependency vibe-d:tls 0.8.2
          Found dependency vibe-d:stream 0.8.2
            Found dependency vibe-d:core 0.8.2
              Found dependency vibe-d:utils 0.8.2
              Found dependency vibe-d:data 0.8.2
              Found dependency libevent 2.0.2+2.0.16
              Found dependency libasync 0.8.3
                Found dependency memutils 0.4.10
              Found dependency vibe-core 1.4.0-alpha.1
                Found dependency stdx-allocator 2.77.0
                Found dependency eventcore 0.8.28
                  Found dependency taggedalgebraic 0.10.9
          Found dependency openssl 1.1.6+1.0.1g
          Found dependency botan 1.12.9
            Found dependency botan-math 1.0.3
        Found dependency vibe-d:crypto 0.8.2
        Found dependency vibe-d:inet 0.8.2
          Found dependency vibe-d:textfilter 0.8.2
        Found dependency diet-ng 1.4.4
    Found dependency vibe-d:mongodb 0.8.2
    Found dependency vibe-d:web 0.8.2
    Found dependency vibe-d:mail 0.8.2
  Found dependency mescheka:telex 0.0.6+commit.2.g6afba55
    Found dependency mescheka:util 0.0.6+commit.2.g6afba55
    Found dependency mescheka:implant 0.0.6+commit.2.g6afba55
      Found dependency kxml >=0.0.0 @../../../../../../home/timoses/.dub/packages/kxml
```

Dub version 1.6.0 works:
```
> dub --version
DUB version 1.6.0, built on Nov  1 2017

> dub upgrade -v
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/timoses/.dub/packages/local-packages.json
Determined package version using GIT: kxml 1.0.1+commit.1.g337ff04
Determined package version using GIT: mescheka 0.0.6+commit.2.g6afba55
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/timoses/.dub/packages/local-packages.json
  Found dependency vibe-d 0.8.2
    Found dependency vibe-d:redis 0.8.2
      Found dependency vibe-d:http 0.8.2
        Found dependency vibe-d:tls 0.8.2
          Found dependency vibe-d:stream 0.8.2
            Found dependency vibe-d:core 0.8.2
              Found dependency vibe-d:utils 0.8.2
              Found dependency vibe-d:data 0.8.2
              Found dependency libevent 2.0.2+2.0.16
              Found dependency libasync 0.8.3
                Found dependency memutils 0.4.10
              Found dependency vibe-core 1.4.0-alpha.1
                Found dependency stdx-allocator 2.77.0
                Found dependency eventcore 0.8.28
                  Found dependency taggedalgebraic 0.10.9
          Found dependency openssl 1.1.6+1.0.1g
          Found dependency botan 1.12.9
            Found dependency botan-math 1.0.3
        Found dependency vibe-d:crypto 0.8.2
        Found dependency vibe-d:inet 0.8.2
          Found dependency vibe-d:textfilter 0.8.2
        Found dependency diet-ng 1.4.4
    Found dependency vibe-d:mongodb 0.8.2
    Found dependency vibe-d:web 0.8.2
    Found dependency vibe-d:mail 0.8.2
  Found dependency mescheka:telex 0.0.6+commit.2.g6afba55
    Found dependency mescheka:util 0.0.6+commit.2.g6afba55
    Found dependency mescheka:implant 0.0.6+commit.2.g6afba55
      Found dependency kxml >=0.0.0 @../../../../../../home/timoses/.dub/packages/kxml
Upgrading project in /media/sf_C_DRIVE/Users/funke_t1/Code/mescheka
Search for versions of vibe-d (1 package suppliers)
Return for vibe-d: [0.8.2, 0.8.1, 0.8.0, 0.7.32, 0.7.31, 0.7.30, 0.7.29, 0.7.28, 0.7.27, 0.7.26, 0.7.25, 0.7.24, 0.7.23, 0.7.22, 0.8.3-rc.1, 0.8.3-beta.1, 0.8.3-alpha.4, 0.8.3-alpha.3, 0.8.3-alpha.2, 0.8.3-alpha.1, 0.8.2-rc.2, 0.8.2-rc.1, 0.8.2-alpha.3, 0.8.2-alpha.2, 0.8.2-alpha.1, 0.8.1-rc.4, 0.8.1-rc.3, 0.8.1-rc.2, 0.8.1-rc.1, 0.8.1-beta.2, 0.8.1-beta.1, 0.8.1-alpha.4, 0.8.1-alpha.3, 0.8.1-alpha.2, 0.8.1-alpha.1, 0.8.0-rc.6, 0.8.0-rc.5, 0.8.0-rc.4, 0.8.0-rc.3, 0.8.0-rc.2, 0.8.0-rc.1, 0.8.0-beta.8, 0.8.0-beta.7, 0.8.0-beta.6, 0.8.0-beta.5, 0.8.0-beta.4, 0.8.0-beta.3, 0.8.0-beta.2, 0.8.0-beta.1, 0.8.0-alpha.1, 0.7.32-rc.1, 0.7.32-alpha.1, 0.7.31-rc.3, 0.7.31-rc.2, 0.7.31-rc.1, 0.7.31-beta.2, 0.7.31-beta.1, 0.7.31-alpha.1, 0.7.30-rc.2, 0.7.30-rc.1, 0.7.30-beta.1, 0.7.30-alpha.5, 0.7.30-alpha.4, 0.7.30-alpha.3, 0.7.30-alpha.2, 0.7.30-alpha.1, 0.7.29-rc.1, 0.7.29-beta.2, 0.7.29-beta.1, 0.7.29-alpha.3, 0.7.29-alpha.2, 0.7.29-alpha.1, 0.7.28-alpha.1, 0.7.27-rc.2, 0.7.27-rc.1, 0.7.27-beta.1, 0.7.27-alpha.3, 0.7.27-alpha.2, 0.7.27-alpha.1, 0.7.26-rc.3, 0.7.26-rc.2, 0.7.26-rc.1, 0.7.26-beta.1, 0.7.26-alpha.3, 0.7.26-alpha.2, 0.7.26-alpha.1, 0.7.25-rc.1, 0.7.25-alpha.1, 0.7.24-rc.2, 0.7.24-rc.1, 0.7.24-beta.4, 0.7.24-beta.3, 0.7.24-beta.2, 0.7.24-beta.1, 0.7.23-rc.4, 0.7.23-rc.3, 0.7.23-rc.2, 0.7.23-rc.1, 0.7.23-beta.2, 0.7.23-beta.1, ~master, ~update_compiler_support, ~issue_1994_json_trailing_comma, ~http_speedup, ~http2-botan-cleanup, ~http2-botan, ~0.7.x]
Search for versions of stdx-allocator (1 package suppliers)
Return for stdx-allocator: [2.77.0, 2.77.0-1, ~master]
Search for versions of libevent (1 package suppliers)
Return for libevent: [2.0.2+2.0.16, 2.0.1+2.0.16, 2.0.0+2.0.16, ~master]
Search for versions of libasync (1 package suppliers)
Return for libasync: [0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.2, ~master, ~remove_mscoff_config, ~patch-1]
Search for versions of memutils (1 package suppliers)
Return for memutils: [0.4.10, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.8, 0.3.7, 0.3.6, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, ~master, ~remove_32mscoff_config]
Search for versions of vibe-core (1 package suppliers)
Return for vibe-core: [1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0, 1.4.0-rc.1, 1.4.0-alpha.1, 1.3.0-rc.2, 1.3.0-rc.1, 1.3.0-alpha.2, 1.3.0-alpha.1, 1.2.1-alpha.2, 1.2.1-alpha.1, 1.0.0-rc.4, 1.0.0-rc.3, 1.0.0-rc.2, 1.0.0-rc.1, 1.0.0-beta.8, 1.0.0-beta.7, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.3, 1.0.0-beta.2, 1.0.0-beta.1, 1.0.0-alpha.14, 1.0.0-alpha.13, 1.0.0-alpha.12, 1.0.0-alpha.11, 1.0.0-alpha.10, 1.0.0-alpha.9, 1.0.0-alpha.8, 1.0.0-alpha.7, 1.0.0-alpha.6, 1.0.0-alpha.5, 1.0.0-alpha.4, 1.0.0-alpha.3, 1.0.0-alpha.2, 1.0.0-alpha.1, ~master, ~reproduce_optlink_issue_18, ~dip1000, ~channels]
Search for versions of eventcore (1 package suppliers)
Return for eventcore: [0.8.29, 0.8.28, 0.8.27, 0.8.26, 0.8.25, 0.8.24, 0.8.23, 0.8.22, 0.8.21, 0.8.20, 0.8.19, 0.8.18, 0.8.17, 0.8.16, 0.8.15, 0.8.14, 0.8.13, 0.8.12, 0.8.11, 0.8.10, 0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.0, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.2, 0.1.1, ~master, ~issue_29_duplicate_object_name, ~fix_winapi_handles]
Search for versions of taggedalgebraic (1 package suppliers)
Return for taggedalgebraic: [0.10.9, 0.10.8, 0.10.7, 0.10.6, 0.10.5, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, ~master, ~opApply]
Search for versions of openssl (1 package suppliers)
Return for openssl: [1.1.6+1.0.1g, 1.1.5+1.0.1g, 1.1.4+1.0.1g, 1.1.3+1.0.1g, 1.1.2+1.0.1g, 1.1.1+1.0.1g, 1.1.0+1.0.1g, 1.0.0+1.0.0e, ~master]
Search for versions of botan (1 package suppliers)
Ignoring version specification (>=0.0.0) for path based dependency ../memutils
Return for botan: [1.12.9, 1.12.8, 1.12.7, 1.12.6, 1.12.5, 1.12.4, 1.12.3, 1.12.2, 1.12.1, 1.12.0, 1.11.14, 1.11.13, 1.11.12, 1.11.11, 1.11.10, ~master, ~merge-new-algos, ~ldc-compat, ~fix-tls]
Search for versions of botan-math (1 package suppliers)
Return for botan-math: [1.0.3, 1.0.2, 1.0.1, 1.0.0, ~master]
Sub package botan:base doesn't exist in botan 1.12.9.
Sub package botan:base doesn't exist in botan 1.12.0.
Sub package botan:base doesn't exist in botan 1.11.14.
Sub package botan:base doesn't exist in botan 1.11.13.
Sub package botan:base doesn't exist in botan 1.11.12.
Sub package botan:base doesn't exist in botan 1.11.11.
Sub package botan:base doesn't exist in botan 1.11.10.
Sub package botan:base doesn't exist in botan ~master.
Sub package botan:base doesn't exist in botan ~merge-new-algos.
Sub package botan:base doesn't exist in botan ~ldc-compat.
Sub package botan:base doesn't exist in botan ~fix-tls.
Sub package botan:compression doesn't exist in botan 1.12.9.
Sub package botan:compression doesn't exist in botan 1.12.0.
Sub package botan:compression doesn't exist in botan 1.11.14.
Sub package botan:compression doesn't exist in botan 1.11.13.
Sub package botan:compression doesn't exist in botan 1.11.12.
Sub package botan:compression doesn't exist in botan 1.11.11.
Sub package botan:compression doesn't exist in botan 1.11.10.
Sub package botan:compression doesn't exist in botan ~master.
Sub package botan:compression doesn't exist in botan ~merge-new-algos.
Sub package botan:compression doesn't exist in botan ~ldc-compat.
Sub package botan:compression doesn't exist in botan ~fix-tls.
Sub package botan:tls doesn't exist in botan 1.12.9.
Sub package botan:tls doesn't exist in botan 1.12.0.
Sub package botan:tls doesn't exist in botan 1.11.14.
Sub package botan:tls doesn't exist in botan 1.11.13.
Sub package botan:tls doesn't exist in botan 1.11.12.
Sub package botan:tls doesn't exist in botan 1.11.11.
Sub package botan:tls doesn't exist in botan 1.11.10.
Sub package botan:tls doesn't exist in botan ~master.
Sub package botan:tls doesn't exist in botan ~merge-new-algos.
Sub package botan:tls doesn't exist in botan ~ldc-compat.
Sub package botan:tls doesn't exist in botan ~fix-tls.
Sub package botan:passhash doesn't exist in botan 1.12.9.
Sub package botan:passhash doesn't exist in botan 1.12.0.
Sub package botan:passhash doesn't exist in botan 1.11.14.
Sub package botan:passhash doesn't exist in botan 1.11.13.
Sub package botan:passhash doesn't exist in botan 1.11.12.
Sub package botan:passhash doesn't exist in botan 1.11.11.
Sub package botan:passhash doesn't exist in botan 1.11.10.
Sub package botan:passhash doesn't exist in botan ~master.
Sub package botan:passhash doesn't exist in botan ~merge-new-algos.
Sub package botan:passhash doesn't exist in botan ~ldc-compat.
Sub package botan:passhash doesn't exist in botan ~fix-tls.
Failed to load path based dependency memutils: No package file found in ../memutils/, expected one of dub.json/dub.sdl/package.json
Search for versions of diet-ng (1 package suppliers)
Return for diet-ng: [1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.0, 1.2.1, 1.2.0, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0, 1.0.0-beta.3, 1.0.0-beta.2, 1.0.0-beta.1, 1.0.0-alpha.2, 1.0.0-alpha.1, ~master, ~dmd_segfault]
Search for versions of kxml (1 package suppliers)
Return for kxml: [1.0.1+commit.1.g337ff04, 1.0.0, ~master]
Fetching vibe-core 1.3.0 (getting selected version)...
Downloading from 'http://code.dlang.org/packages/vibe-core/1.3.0.zip'
Placing to /home/timoses/.dub/packages/...
Fetching eventcore 0.8.29 (getting selected version)...
Downloading from 'http://code.dlang.org/packages/eventcore/0.8.29.zip'
Placing to /home/timoses/.dub/packages/...
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/timoses/.dub/packages/local-packages.json
  Found dependency vibe-d 0.8.2
    Found dependency vibe-d:redis 0.8.2
      Found dependency vibe-d:http 0.8.2
        Found dependency vibe-d:tls 0.8.2
          Found dependency vibe-d:stream 0.8.2
            Found dependency vibe-d:core 0.8.2
              Found dependency vibe-d:utils 0.8.2
              Found dependency vibe-d:data 0.8.2
              Found dependency libevent 2.0.2+2.0.16
              Found dependency libasync 0.8.3
                Found dependency memutils 0.4.10
              Found dependency vibe-core 1.3.0
                Found dependency eventcore 0.8.29
                  Found dependency taggedalgebraic 0.10.9
          Found dependency openssl 1.1.6+1.0.1g
          Found dependency botan 1.12.9
            Found dependency botan-math 1.0.3
        Found dependency vibe-d:crypto 0.8.2
        Found dependency vibe-d:inet 0.8.2
          Found dependency vibe-d:textfilter 0.8.2
        Found dependency diet-ng 1.4.4
    Found dependency vibe-d:mongodb 0.8.2
    Found dependency vibe-d:web 0.8.2
    Found dependency vibe-d:mail 0.8.2
  Found dependency mescheka:telex 0.0.6+commit.2.g6afba55
    Found dependency mescheka:util 0.0.6+commit.2.g6afba55
    Found dependency mescheka:implant 0.0.6+commit.2.g6afba55
      Found dependency kxml >=0.0.0 @../../../../../../home/timoses/.dub/packages/kxml
```

**Comment by Timoses** [comment] 2018-03-07 11:06
Another side effect seems to be that building subpackages also fails with the same error:
```
> git clone https://github.com/vibe-d/vibe.d
> cd vibe.d/http
> dub build
Package vibe-d not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Package stdx-allocator not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
Package libevent not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 0 ()
```

**Comment by s-ludwig** [comment] 2018-03-07 11:18
Is the "http_proxy" environment variable set with the required proxy address? This is what is used to configure cURL in DUB and I think that it doesn't use any other configuration sources.

Not sure why it has stopped working, the network access has always been based on libcurl. The only recent changes in this area are a connection timeout and the retry logic.

Maybe related: https://github.com/dlang/dub/issues/1373#issuecomment-366516581

**Comment by Timoses** [comment] 2018-03-07 11:27
$http_proxy and $https_proxy are set.

### Update:
Curl to http works, but not to https.
**Wget works with both, http and https.**
It's another story (can't seem to set up the corporate certificates correctly).

Why though does it work with dub version 1.6.0 anyway?

I do indeed receive the same error message:
```
Full error: std.net.curl.HTTPStatusException@/usr/lib/gcc/x86_64-linux-gnu/8/include/d/std/net/curl.d(1050): HTTP request returned status code 0 ()
----------------
0x55eea3a95d68 ???
	???:0
0x55eea3b150e5 ???
	???:0
0x55eea3b1531b ???
	???:0
0x55eea3a1d3e0 ???
	???:0
0x55eea3a616a2 ???
	???:0
0x55eea3a61cd0 ???
	???:0
0x55eea3b48bab ???
	???:0
0x55eea3a6d1d7 ???
	???:0
0x55eea3ab6cb6 ???
	???:0
0x55eea3b8c19e ???
	???:0
0x55eea3a4db75 ???
	???:0
0x55eea3a409da ???
	???:0
0x55eea3a1d501 ???
	???:0
0x55eea3a6474e ???
	???:0
0x55eea3ca20fe ???
	???:0
0x55eea3ca227d ???
	???:0
0x55eea3ca259a ???
	???:0
0x55eea3ca227d ???
	???:0
0x55eea3ca23e4 ???
	???:0
0x7f61661d62b0 __libc_start_main
	???:0
0x55eea39eac19 ???
	???:0
0xffffffffffffffff ???
	???:0
```

**Comment by Geod24** [comment] 2022-08-06 14:33
This may have been caused by a few reasons, one of them being the registry going to HTTP/2 and cURL not supporting it.
In any case, if the registry was down / unusable at the moment, we would know about it, so I think it's safe to close this.

**Closed by Geod24** 2022-08-06 14:33 UTC
