### ISSUE TITLE
Skip registry upgrade only

### ISSUE THREAD

**Issue by rikkimax** [dlang/dub#2244] opened 2022-04-26 16:59 UTC
It would be a good addition to add support for skipping the registry unless an explicit call to upgrade or if dub.selections.json becomes out of sync from the package descriptor.

Reference: https://forum.dlang.org/post/t4986c$1r40$1@digitalmars.com

**Comment by WebFreak001** [comment] 2023-02-16 20:53
duplicate of #559

copying my response for closing:

DUB doesn't check for package updates when packages are already fetched & selected inside the dub.selections.json.

DUB only checks for upgrades:

1. with branch-based dependencies (`~master`) - they are discouraged/deprecated
2. for packages that don't have any selection yet in dub.selections.json or are not yet downloaded

Forcing no internet lookup (and causing a build fail for missing dependencies) can be forced with `--nodeps`

**Closed by WebFreak001** 2023-02-16 20:53 UTC
