### ISSUE TITLE
AssertError @source\dub\internal\vibecompat\core\log.d(85): (Bad file descriptor)

### ISSUE THREAD

**Issue by bruno-medeiros** [dlang/dub#892] opened 2016-07-06 17:21 UTC
Seems to happen when I start up Eclipse, which makes it call `dub describe` on multiple projects. Happens with DUB 1.0, but also with previous version of DUB. Only started happening recently though, I'm not sure what changed. I'll see if can try to pinpoint the steps to reproduce.

Windows 7 64bit.

Here is the stack trace:
![untitled](https://cloud.githubusercontent.com/assets/4324232/16627652/1728f472-43a6-11e6-8e88-01b3218dc6a5.png)
(I couldn't select the text in that pop-up, so I had to take screenshot)

**Comment by s-ludwig** [comment] 2016-07-06 17:29
Are `stdout` and `stderr` redirected, or is maybe one of them not bound? Nothing changed in that area, but maybe the difference is that DUB now outputs a warning or an error (i.e. to `stderr`)? In any case, I'll add a check to `File.isOpen` - hopefully that will return `false` if the FD is invalid.

**Comment by s-ludwig** [comment] 2016-07-06 17:33
Pushed the check. Can you test if that avoids the assertion?

**Comment by bruno-medeiros** [comment] 2016-07-06 18:25
stdout and stderr are indeed redirected. Following your hint, I figured how to reproduce it: Basically I kill the Eclipse process whilst a `dub describe` is happening. Typically this only happens when I am debugging Eclipse DDT itself (normal Eclipse termination will terminate spawned dub processes).

I'll try your fix, do I just need to build DUB with `build.cmd`?

**Comment by bruno-medeiros** [comment] 2016-07-06 20:00
Nevermind, I just built DUB with `build.cmd`, and tried it. The same assertion still occurs though.

**Comment by s-ludwig** [comment] 2016-07-27 08:31
I wonder if the assertion should simply be replaced by something like this:
```
try stderr.writeln("Failed to write log message: " ~ e.msg);
catch (Exception e) {} // ignore

**Comment by WebFreak001** [comment] 2023-02-17 01:44
closing this because no reproduction possible

**Closed by WebFreak001** 2023-02-17 01:44 UTC
